// @generated by scripts/generate_feedback_contracts.mjs; do not edit.

export const FEEDBACK_SCHEMA_VERSION = 1 as const;

export const FEEDBACK_PRIVACY_CLASSES = [
  "operational",
  "circuit-derived",
  "user-content",
] as const;
export type FeedbackPrivacyClass = (typeof FEEDBACK_PRIVACY_CLASSES)[number];

export const FEEDBACK_EVENT_KINDS = [
  "session.started",
  "session.ended",
  "circuit.summary_created",
  "erc.completed",
  "simulation.started",
  "simulation.completed",
  "simulation.failed",
  "simulation.cancelled",
  "solver.convergence_summary",
  "performance.sampled",
  "parser.completed",
  "ui.error_observed",
  "recommendation.shown",
  "recommendation.outcome",
  "user.feedback_submitted",
  "validation.case_completed",
  "export.created",
  "data.deleted",
] as const;
export type FeedbackEventKind = (typeof FEEDBACK_EVENT_KINDS)[number];

export const FEEDBACK_EVENT_PRIVACY = {
  "session.started": "operational",
  "session.ended": "operational",
  "circuit.summary_created": "circuit-derived",
  "erc.completed": "circuit-derived",
  "simulation.started": "circuit-derived",
  "simulation.completed": "operational",
  "simulation.failed": "operational",
  "simulation.cancelled": "operational",
  "solver.convergence_summary": "operational",
  "performance.sampled": "operational",
  "parser.completed": "circuit-derived",
  "ui.error_observed": "operational",
  "recommendation.shown": "operational",
  "recommendation.outcome": "operational",
  "user.feedback_submitted": "user-content",
  "validation.case_completed": "circuit-derived",
  "export.created": "operational",
  "data.deleted": "operational",
} as const satisfies Readonly<Record<FeedbackEventKind, FeedbackPrivacyClass>>;

export interface FeedbackEventEnvelopeV1 {
  readonly schemaVersion: typeof FEEDBACK_SCHEMA_VERSION;
  readonly eventId: string;
  readonly occurredAtUnixMs: number;
  readonly sessionId: string;
  readonly runId?: string;
  readonly workspaceId?: string;
  readonly appVersion: string;
  readonly gitRevision?: string;
}

export interface SessionStartedPayloadV1 {
  readonly previousSessionId?: string;
  readonly os: string;
  readonly locale?: string;
}

export interface SessionEndedPayloadV1 {
  readonly durationMs: number;
  readonly cleanShutdown: boolean;
}

export interface CircuitSummaryCreatedPayloadV1 {
  readonly topologyFingerprint: string;
  readonly componentCount: number;
  readonly nodeCount: number;
  readonly wireCount: number;
  readonly nonlinearDeviceCount: number;
  readonly reactiveDeviceCount: number;
  readonly componentHistogram: Readonly<Record<string, number>>;
  readonly containsFirmware: boolean;
}

export interface ErcCompletedPayloadV1 {
  readonly passed: boolean;
  readonly errorCount: number;
  readonly warningCount: number;
  readonly codeCounts: Readonly<Record<string, number>>;
  readonly durationMs: number;
}

export interface SimulationStartedPayloadV1 {
  readonly analysis: "DC" | "DC_SWEEP" | "AC" | "TRAN" | "TRAN_MC" | "SENS" | "PSS" | "STB" | "PVT" | "SPAR" | "FFT" | "IMD" | "NOISE" | "THERMAL";
  readonly settingsFingerprint: string;
  readonly componentCount: number;
  readonly nodeCount: number;
  readonly requestedPointCount?: number;
}

export interface SimulationCompletedPayloadV1 {
  readonly analysis: "DC" | "DC_SWEEP" | "AC" | "TRAN" | "TRAN_MC" | "SENS" | "PSS" | "STB" | "PVT" | "SPAR" | "FFT" | "IMD" | "NOISE" | "THERMAL";
  readonly durationMs: number;
  readonly pointCount: number;
  readonly converged: boolean;
  readonly finalResidual?: number;
}

export interface SimulationFailedPayloadV1 {
  readonly analysis: "DC" | "DC_SWEEP" | "AC" | "TRAN" | "TRAN_MC" | "SENS" | "PSS" | "STB" | "PVT" | "SPAR" | "FFT" | "IMD" | "NOISE" | "THERMAL";
  readonly phase: "preflight" | "extraction" | "stamping" | "iteration" | "serialization" | "ipc" | "unknown";
  readonly errorCode: string;
  readonly messageFingerprint: string;
  readonly durationMs: number;
}

export interface SimulationCancelledPayloadV1 {
  readonly reason: "user" | "replaced" | "shutdown" | "timeout";
  readonly durationMs: number;
}

export interface SolverConvergenceSummaryPayloadV1 {
  readonly analysis: "DC" | "DC_SWEEP" | "AC" | "TRAN" | "TRAN_MC" | "SENS" | "PSS" | "STB" | "PVT" | "SPAR" | "FFT" | "IMD" | "NOISE" | "THERMAL";
  readonly method: string;
  readonly iterations: number;
  readonly acceptedSteps: number;
  readonly rejectedSteps: number;
  readonly finalResidual?: number;
  readonly homotopyUsed: boolean;
}

export interface PerformanceSampledPayloadV1 {
  readonly fps: number;
  readonly cpuPercent: number;
  readonly ramBytes: number;
  readonly canvasFrames: number;
  readonly oscilloscopeFrames: number;
  readonly skippedDmmUpdates: number;
}

export interface ParserCompletedPayloadV1 {
  readonly format: "spice";
  readonly success: boolean;
  readonly componentCount: number;
  readonly durationMs: number;
  readonly errorCode?: string;
}

export interface UiErrorObservedPayloadV1 {
  readonly area: "simulation" | "parser" | "export" | "canvas" | "file" | "settings" | "unknown";
  readonly errorCode: string;
  readonly messageFingerprint: string;
}

export interface RecommendationShownPayloadV1 {
  readonly recommendationId: string;
  readonly ruleId: string;
  readonly safetyClass: "informational" | "reversible" | "scientific-review-required";
  readonly confidence: number;
  readonly proposedProfile?: string;
}

export interface RecommendationOutcomePayloadV1 {
  readonly recommendationId: string;
  readonly decision: "accepted" | "rejected" | "dismissed";
  readonly applied: boolean;
  readonly improved?: boolean;
  readonly deltaDurationPercent?: number;
}

export interface UserFeedbackSubmittedPayloadV1 {
  readonly subjectEventId?: string;
  readonly rating: "correct" | "uncertain" | "incorrect";
  readonly category: "convergence" | "performance" | "interface" | "model" | "other";
  readonly expectedValue?: number;
  readonly expectedUnit?: string;
  readonly note?: string;
  readonly noteFingerprint?: string;
  readonly attachmentIncluded: boolean;
}

export interface ValidationCaseCompletedPayloadV1 {
  readonly caseId: string;
  readonly analysis: "DC" | "DC_SWEEP" | "AC" | "TRAN" | "TRAN_MC" | "SENS" | "PSS" | "STB" | "PVT" | "SPAR" | "FFT" | "IMD" | "NOISE" | "THERMAL";
  readonly passed: boolean;
  readonly observationCount: number;
  readonly maxNormalizedError: number;
  readonly referenceMethod: "closed-form" | "ngspice-live" | "measurement" | "other";
}

export interface ExportCreatedPayloadV1 {
  readonly exportKind: "support-bundle" | "touchstone" | "csv" | "svg" | "hdf5" | "pdf";
  readonly itemCount: number;
  readonly redactionCount: number;
}

export interface DataDeletedPayloadV1 {
  readonly scope: "all" | "expired" | "session";
  readonly rowsDeleted: number;
  readonly attachmentsDeleted: number;
}

export type FeedbackEventV1 =
  (FeedbackEventEnvelopeV1 & { readonly privacyClass: "operational"; readonly kind: "session.started"; readonly payload: SessionStartedPayloadV1 })
  | (FeedbackEventEnvelopeV1 & { readonly privacyClass: "operational"; readonly kind: "session.ended"; readonly payload: SessionEndedPayloadV1 })
  | (FeedbackEventEnvelopeV1 & { readonly privacyClass: "circuit-derived"; readonly kind: "circuit.summary_created"; readonly payload: CircuitSummaryCreatedPayloadV1 })
  | (FeedbackEventEnvelopeV1 & { readonly privacyClass: "circuit-derived"; readonly kind: "erc.completed"; readonly payload: ErcCompletedPayloadV1 })
  | (FeedbackEventEnvelopeV1 & { readonly privacyClass: "circuit-derived"; readonly kind: "simulation.started"; readonly payload: SimulationStartedPayloadV1 })
  | (FeedbackEventEnvelopeV1 & { readonly privacyClass: "operational"; readonly kind: "simulation.completed"; readonly payload: SimulationCompletedPayloadV1 })
  | (FeedbackEventEnvelopeV1 & { readonly privacyClass: "operational"; readonly kind: "simulation.failed"; readonly payload: SimulationFailedPayloadV1 })
  | (FeedbackEventEnvelopeV1 & { readonly privacyClass: "operational"; readonly kind: "simulation.cancelled"; readonly payload: SimulationCancelledPayloadV1 })
  | (FeedbackEventEnvelopeV1 & { readonly privacyClass: "operational"; readonly kind: "solver.convergence_summary"; readonly payload: SolverConvergenceSummaryPayloadV1 })
  | (FeedbackEventEnvelopeV1 & { readonly privacyClass: "operational"; readonly kind: "performance.sampled"; readonly payload: PerformanceSampledPayloadV1 })
  | (FeedbackEventEnvelopeV1 & { readonly privacyClass: "circuit-derived"; readonly kind: "parser.completed"; readonly payload: ParserCompletedPayloadV1 })
  | (FeedbackEventEnvelopeV1 & { readonly privacyClass: "operational"; readonly kind: "ui.error_observed"; readonly payload: UiErrorObservedPayloadV1 })
  | (FeedbackEventEnvelopeV1 & { readonly privacyClass: "operational"; readonly kind: "recommendation.shown"; readonly payload: RecommendationShownPayloadV1 })
  | (FeedbackEventEnvelopeV1 & { readonly privacyClass: "operational"; readonly kind: "recommendation.outcome"; readonly payload: RecommendationOutcomePayloadV1 })
  | (FeedbackEventEnvelopeV1 & { readonly privacyClass: "user-content"; readonly kind: "user.feedback_submitted"; readonly payload: UserFeedbackSubmittedPayloadV1 })
  | (FeedbackEventEnvelopeV1 & { readonly privacyClass: "circuit-derived"; readonly kind: "validation.case_completed"; readonly payload: ValidationCaseCompletedPayloadV1 })
  | (FeedbackEventEnvelopeV1 & { readonly privacyClass: "operational"; readonly kind: "export.created"; readonly payload: ExportCreatedPayloadV1 })
  | (FeedbackEventEnvelopeV1 & { readonly privacyClass: "operational"; readonly kind: "data.deleted"; readonly payload: DataDeletedPayloadV1 })
;

export function expectedPrivacyClass(kind: FeedbackEventKind): FeedbackPrivacyClass {
  return FEEDBACK_EVENT_PRIVACY[kind];
}
