// @generated by scripts/generate_feedback_contracts.mjs; do not edit.
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;

pub const FEEDBACK_SCHEMA_VERSION: u16 = 1;

#[derive(Serialize, Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum FeedbackPrivacyClass {
    #[serde(rename = "operational")]
    Operational,
    #[serde(rename = "circuit-derived")]
    CircuitDerived,
    #[serde(rename = "user-content")]
    UserContent,
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct SessionStartedPayloadV1 {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub previous_session_id: Option<String>,
    pub os: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub locale: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct SessionEndedPayloadV1 {
    pub duration_ms: u64,
    pub clean_shutdown: bool,
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct CircuitSummaryCreatedPayloadV1 {
    pub topology_fingerprint: String,
    pub component_count: u64,
    pub node_count: u64,
    pub wire_count: u64,
    pub nonlinear_device_count: u64,
    pub reactive_device_count: u64,
    pub component_histogram: BTreeMap<String, u64>,
    pub contains_firmware: bool,
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct ErcCompletedPayloadV1 {
    pub passed: bool,
    pub error_count: u64,
    pub warning_count: u64,
    pub code_counts: BTreeMap<String, u64>,
    pub duration_ms: f64,
}

#[derive(Serialize, Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum SimulationStartedAnalysisValue {
    #[serde(rename = "DC")]
    Dc,
    #[serde(rename = "DC_SWEEP")]
    DcSweep,
    #[serde(rename = "AC")]
    Ac,
    #[serde(rename = "TRAN")]
    Tran,
    #[serde(rename = "TRAN_MC")]
    TranMc,
    #[serde(rename = "SENS")]
    Sens,
    #[serde(rename = "PSS")]
    Pss,
    #[serde(rename = "STB")]
    Stb,
    #[serde(rename = "PVT")]
    Pvt,
    #[serde(rename = "SPAR")]
    Spar,
    #[serde(rename = "FFT")]
    Fft,
    #[serde(rename = "IMD")]
    Imd,
    #[serde(rename = "NOISE")]
    Noise,
    #[serde(rename = "THERMAL")]
    Thermal,
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct SimulationStartedPayloadV1 {
    pub analysis: SimulationStartedAnalysisValue,
    pub settings_fingerprint: String,
    pub component_count: u64,
    pub node_count: u64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub requested_point_count: Option<u64>,
}

#[derive(Serialize, Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum SimulationCompletedAnalysisValue {
    #[serde(rename = "DC")]
    Dc,
    #[serde(rename = "DC_SWEEP")]
    DcSweep,
    #[serde(rename = "AC")]
    Ac,
    #[serde(rename = "TRAN")]
    Tran,
    #[serde(rename = "TRAN_MC")]
    TranMc,
    #[serde(rename = "SENS")]
    Sens,
    #[serde(rename = "PSS")]
    Pss,
    #[serde(rename = "STB")]
    Stb,
    #[serde(rename = "PVT")]
    Pvt,
    #[serde(rename = "SPAR")]
    Spar,
    #[serde(rename = "FFT")]
    Fft,
    #[serde(rename = "IMD")]
    Imd,
    #[serde(rename = "NOISE")]
    Noise,
    #[serde(rename = "THERMAL")]
    Thermal,
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct SimulationCompletedPayloadV1 {
    pub analysis: SimulationCompletedAnalysisValue,
    pub duration_ms: f64,
    pub point_count: u64,
    pub converged: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub final_residual: Option<f64>,
}

#[derive(Serialize, Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum SimulationFailedAnalysisValue {
    #[serde(rename = "DC")]
    Dc,
    #[serde(rename = "DC_SWEEP")]
    DcSweep,
    #[serde(rename = "AC")]
    Ac,
    #[serde(rename = "TRAN")]
    Tran,
    #[serde(rename = "TRAN_MC")]
    TranMc,
    #[serde(rename = "SENS")]
    Sens,
    #[serde(rename = "PSS")]
    Pss,
    #[serde(rename = "STB")]
    Stb,
    #[serde(rename = "PVT")]
    Pvt,
    #[serde(rename = "SPAR")]
    Spar,
    #[serde(rename = "FFT")]
    Fft,
    #[serde(rename = "IMD")]
    Imd,
    #[serde(rename = "NOISE")]
    Noise,
    #[serde(rename = "THERMAL")]
    Thermal,
}

#[derive(Serialize, Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum SimulationFailedPhaseValue {
    #[serde(rename = "preflight")]
    Preflight,
    #[serde(rename = "extraction")]
    Extraction,
    #[serde(rename = "stamping")]
    Stamping,
    #[serde(rename = "iteration")]
    Iteration,
    #[serde(rename = "serialization")]
    Serialization,
    #[serde(rename = "ipc")]
    Ipc,
    #[serde(rename = "unknown")]
    Unknown,
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct SimulationFailedPayloadV1 {
    pub analysis: SimulationFailedAnalysisValue,
    pub phase: SimulationFailedPhaseValue,
    pub error_code: String,
    pub message_fingerprint: String,
    pub duration_ms: f64,
}

#[derive(Serialize, Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum SimulationCancelledReasonValue {
    #[serde(rename = "user")]
    User,
    #[serde(rename = "replaced")]
    Replaced,
    #[serde(rename = "shutdown")]
    Shutdown,
    #[serde(rename = "timeout")]
    Timeout,
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct SimulationCancelledPayloadV1 {
    pub reason: SimulationCancelledReasonValue,
    pub duration_ms: f64,
}

#[derive(Serialize, Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum SolverConvergenceSummaryAnalysisValue {
    #[serde(rename = "DC")]
    Dc,
    #[serde(rename = "DC_SWEEP")]
    DcSweep,
    #[serde(rename = "AC")]
    Ac,
    #[serde(rename = "TRAN")]
    Tran,
    #[serde(rename = "TRAN_MC")]
    TranMc,
    #[serde(rename = "SENS")]
    Sens,
    #[serde(rename = "PSS")]
    Pss,
    #[serde(rename = "STB")]
    Stb,
    #[serde(rename = "PVT")]
    Pvt,
    #[serde(rename = "SPAR")]
    Spar,
    #[serde(rename = "FFT")]
    Fft,
    #[serde(rename = "IMD")]
    Imd,
    #[serde(rename = "NOISE")]
    Noise,
    #[serde(rename = "THERMAL")]
    Thermal,
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct SolverConvergenceSummaryPayloadV1 {
    pub analysis: SolverConvergenceSummaryAnalysisValue,
    pub method: String,
    pub iterations: u64,
    pub accepted_steps: u64,
    pub rejected_steps: u64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub final_residual: Option<f64>,
    pub homotopy_used: bool,
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct PerformanceSampledPayloadV1 {
    pub fps: f64,
    pub cpu_percent: f64,
    pub ram_bytes: u64,
    pub canvas_frames: u64,
    pub oscilloscope_frames: u64,
    pub skipped_dmm_updates: u64,
}

#[derive(Serialize, Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum ParserCompletedFormatValue {
    #[serde(rename = "spice")]
    Spice,
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct ParserCompletedPayloadV1 {
    pub format: ParserCompletedFormatValue,
    pub success: bool,
    pub component_count: u64,
    pub duration_ms: f64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error_code: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum UiErrorObservedAreaValue {
    #[serde(rename = "simulation")]
    Simulation,
    #[serde(rename = "parser")]
    Parser,
    #[serde(rename = "export")]
    Export,
    #[serde(rename = "canvas")]
    Canvas,
    #[serde(rename = "file")]
    File,
    #[serde(rename = "settings")]
    Settings,
    #[serde(rename = "unknown")]
    Unknown,
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct UiErrorObservedPayloadV1 {
    pub area: UiErrorObservedAreaValue,
    pub error_code: String,
    pub message_fingerprint: String,
}

#[derive(Serialize, Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum RecommendationShownSafetyclassValue {
    #[serde(rename = "informational")]
    Informational,
    #[serde(rename = "reversible")]
    Reversible,
    #[serde(rename = "scientific-review-required")]
    ScientificReviewRequired,
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct RecommendationShownPayloadV1 {
    pub recommendation_id: String,
    pub rule_id: String,
    pub safety_class: RecommendationShownSafetyclassValue,
    pub confidence: f64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub proposed_profile: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum RecommendationOutcomeDecisionValue {
    #[serde(rename = "accepted")]
    Accepted,
    #[serde(rename = "rejected")]
    Rejected,
    #[serde(rename = "dismissed")]
    Dismissed,
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct RecommendationOutcomePayloadV1 {
    pub recommendation_id: String,
    pub decision: RecommendationOutcomeDecisionValue,
    pub applied: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub improved: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub delta_duration_percent: Option<f64>,
}

#[derive(Serialize, Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum UserFeedbackSubmittedRatingValue {
    #[serde(rename = "correct")]
    Correct,
    #[serde(rename = "uncertain")]
    Uncertain,
    #[serde(rename = "incorrect")]
    Incorrect,
}

#[derive(Serialize, Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum UserFeedbackSubmittedCategoryValue {
    #[serde(rename = "convergence")]
    Convergence,
    #[serde(rename = "performance")]
    Performance,
    #[serde(rename = "interface")]
    Interface,
    #[serde(rename = "model")]
    Model,
    #[serde(rename = "other")]
    Other,
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct UserFeedbackSubmittedPayloadV1 {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub subject_event_id: Option<String>,
    pub rating: UserFeedbackSubmittedRatingValue,
    pub category: UserFeedbackSubmittedCategoryValue,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub expected_value: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub expected_unit: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub note_fingerprint: Option<String>,
    pub attachment_included: bool,
}

#[derive(Serialize, Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum ValidationCaseCompletedAnalysisValue {
    #[serde(rename = "DC")]
    Dc,
    #[serde(rename = "DC_SWEEP")]
    DcSweep,
    #[serde(rename = "AC")]
    Ac,
    #[serde(rename = "TRAN")]
    Tran,
    #[serde(rename = "TRAN_MC")]
    TranMc,
    #[serde(rename = "SENS")]
    Sens,
    #[serde(rename = "PSS")]
    Pss,
    #[serde(rename = "STB")]
    Stb,
    #[serde(rename = "PVT")]
    Pvt,
    #[serde(rename = "SPAR")]
    Spar,
    #[serde(rename = "FFT")]
    Fft,
    #[serde(rename = "IMD")]
    Imd,
    #[serde(rename = "NOISE")]
    Noise,
    #[serde(rename = "THERMAL")]
    Thermal,
}

#[derive(Serialize, Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum ValidationCaseCompletedReferencemethodValue {
    #[serde(rename = "closed-form")]
    ClosedForm,
    #[serde(rename = "ngspice-live")]
    NgspiceLive,
    #[serde(rename = "measurement")]
    Measurement,
    #[serde(rename = "other")]
    Other,
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct ValidationCaseCompletedPayloadV1 {
    pub case_id: String,
    pub analysis: ValidationCaseCompletedAnalysisValue,
    pub passed: bool,
    pub observation_count: u64,
    pub max_normalized_error: f64,
    pub reference_method: ValidationCaseCompletedReferencemethodValue,
}

#[derive(Serialize, Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum ExportCreatedExportkindValue {
    #[serde(rename = "support-bundle")]
    SupportBundle,
    #[serde(rename = "touchstone")]
    Touchstone,
    #[serde(rename = "csv")]
    Csv,
    #[serde(rename = "svg")]
    Svg,
    #[serde(rename = "hdf5")]
    Hdf5,
    #[serde(rename = "pdf")]
    Pdf,
    #[serde(rename = "json")]
    Json,
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct ExportCreatedPayloadV1 {
    pub export_kind: ExportCreatedExportkindValue,
    pub item_count: u64,
    pub redaction_count: u64,
}

#[derive(Serialize, Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum DataDeletedScopeValue {
    #[serde(rename = "all")]
    All,
    #[serde(rename = "expired")]
    Expired,
    #[serde(rename = "session")]
    Session,
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct DataDeletedPayloadV1 {
    pub scope: DataDeletedScopeValue,
    pub rows_deleted: u64,
    pub attachments_deleted: u64,
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
#[serde(tag = "kind", content = "payload")]
pub enum FeedbackEventDataV1 {
    #[serde(rename = "session.started")]
    SessionStarted(SessionStartedPayloadV1),
    #[serde(rename = "session.ended")]
    SessionEnded(SessionEndedPayloadV1),
    #[serde(rename = "circuit.summary_created")]
    CircuitSummaryCreated(CircuitSummaryCreatedPayloadV1),
    #[serde(rename = "erc.completed")]
    ErcCompleted(ErcCompletedPayloadV1),
    #[serde(rename = "simulation.started")]
    SimulationStarted(SimulationStartedPayloadV1),
    #[serde(rename = "simulation.completed")]
    SimulationCompleted(SimulationCompletedPayloadV1),
    #[serde(rename = "simulation.failed")]
    SimulationFailed(SimulationFailedPayloadV1),
    #[serde(rename = "simulation.cancelled")]
    SimulationCancelled(SimulationCancelledPayloadV1),
    #[serde(rename = "solver.convergence_summary")]
    SolverConvergenceSummary(SolverConvergenceSummaryPayloadV1),
    #[serde(rename = "performance.sampled")]
    PerformanceSampled(PerformanceSampledPayloadV1),
    #[serde(rename = "parser.completed")]
    ParserCompleted(ParserCompletedPayloadV1),
    #[serde(rename = "ui.error_observed")]
    UiErrorObserved(UiErrorObservedPayloadV1),
    #[serde(rename = "recommendation.shown")]
    RecommendationShown(RecommendationShownPayloadV1),
    #[serde(rename = "recommendation.outcome")]
    RecommendationOutcome(RecommendationOutcomePayloadV1),
    #[serde(rename = "user.feedback_submitted")]
    UserFeedbackSubmitted(UserFeedbackSubmittedPayloadV1),
    #[serde(rename = "validation.case_completed")]
    ValidationCaseCompleted(ValidationCaseCompletedPayloadV1),
    #[serde(rename = "export.created")]
    ExportCreated(ExportCreatedPayloadV1),
    #[serde(rename = "data.deleted")]
    DataDeleted(DataDeletedPayloadV1),
}

impl FeedbackEventDataV1 {
    pub fn kind(&self) -> &'static str {
        match self {
            Self::SessionStarted(_) => "session.started",
            Self::SessionEnded(_) => "session.ended",
            Self::CircuitSummaryCreated(_) => "circuit.summary_created",
            Self::ErcCompleted(_) => "erc.completed",
            Self::SimulationStarted(_) => "simulation.started",
            Self::SimulationCompleted(_) => "simulation.completed",
            Self::SimulationFailed(_) => "simulation.failed",
            Self::SimulationCancelled(_) => "simulation.cancelled",
            Self::SolverConvergenceSummary(_) => "solver.convergence_summary",
            Self::PerformanceSampled(_) => "performance.sampled",
            Self::ParserCompleted(_) => "parser.completed",
            Self::UiErrorObserved(_) => "ui.error_observed",
            Self::RecommendationShown(_) => "recommendation.shown",
            Self::RecommendationOutcome(_) => "recommendation.outcome",
            Self::UserFeedbackSubmitted(_) => "user.feedback_submitted",
            Self::ValidationCaseCompleted(_) => "validation.case_completed",
            Self::ExportCreated(_) => "export.created",
            Self::DataDeleted(_) => "data.deleted",
        }
    }

    pub fn expected_privacy_class(&self) -> FeedbackPrivacyClass {
        match self {
            Self::SessionStarted(_) => FeedbackPrivacyClass::Operational,
            Self::SessionEnded(_) => FeedbackPrivacyClass::Operational,
            Self::CircuitSummaryCreated(_) => FeedbackPrivacyClass::CircuitDerived,
            Self::ErcCompleted(_) => FeedbackPrivacyClass::CircuitDerived,
            Self::SimulationStarted(_) => FeedbackPrivacyClass::CircuitDerived,
            Self::SimulationCompleted(_) => FeedbackPrivacyClass::Operational,
            Self::SimulationFailed(_) => FeedbackPrivacyClass::Operational,
            Self::SimulationCancelled(_) => FeedbackPrivacyClass::Operational,
            Self::SolverConvergenceSummary(_) => FeedbackPrivacyClass::Operational,
            Self::PerformanceSampled(_) => FeedbackPrivacyClass::Operational,
            Self::ParserCompleted(_) => FeedbackPrivacyClass::CircuitDerived,
            Self::UiErrorObserved(_) => FeedbackPrivacyClass::Operational,
            Self::RecommendationShown(_) => FeedbackPrivacyClass::Operational,
            Self::RecommendationOutcome(_) => FeedbackPrivacyClass::Operational,
            Self::UserFeedbackSubmitted(_) => FeedbackPrivacyClass::UserContent,
            Self::ValidationCaseCompleted(_) => FeedbackPrivacyClass::CircuitDerived,
            Self::ExportCreated(_) => FeedbackPrivacyClass::Operational,
            Self::DataDeleted(_) => FeedbackPrivacyClass::Operational,
        }
    }
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct FeedbackEventV1 {
    pub schema_version: u16,
    pub event_id: String,
    pub occurred_at_unix_ms: u64,
    pub session_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub run_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub workspace_id: Option<String>,
    pub app_version: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub git_revision: Option<String>,
    pub privacy_class: FeedbackPrivacyClass,
    #[serde(flatten)]
    pub event: FeedbackEventDataV1,
}

impl FeedbackEventV1 {
    pub fn validate_envelope(&self) -> Result<(), &'static str> {
        if self.schema_version != FEEDBACK_SCHEMA_VERSION {
            return Err("unsupported schemaVersion");
        }
        if self.event_id.is_empty() || self.event_id.len() > 128 {
            return Err("invalid eventId");
        }
        if self.session_id.is_empty() || self.session_id.len() > 128 {
            return Err("invalid sessionId");
        }
        if self
            .workspace_id
            .as_ref()
            .is_some_and(|value| value.is_empty() || value.len() > 128)
        {
            return Err("invalid workspaceId");
        }
        if self.app_version.is_empty() || self.app_version.len() > 64 {
            return Err("invalid appVersion");
        }
        if self.privacy_class != self.event.expected_privacy_class() {
            return Err("privacyClass does not match event kind");
        }
        Ok(())
    }
}

pub const FEEDBACK_EVENT_CATALOG: &[(&str, FeedbackPrivacyClass)] = &[
    ("session.started", FeedbackPrivacyClass::Operational),
    ("session.ended", FeedbackPrivacyClass::Operational),
    (
        "circuit.summary_created",
        FeedbackPrivacyClass::CircuitDerived,
    ),
    ("erc.completed", FeedbackPrivacyClass::CircuitDerived),
    ("simulation.started", FeedbackPrivacyClass::CircuitDerived),
    ("simulation.completed", FeedbackPrivacyClass::Operational),
    ("simulation.failed", FeedbackPrivacyClass::Operational),
    ("simulation.cancelled", FeedbackPrivacyClass::Operational),
    (
        "solver.convergence_summary",
        FeedbackPrivacyClass::Operational,
    ),
    ("performance.sampled", FeedbackPrivacyClass::Operational),
    ("parser.completed", FeedbackPrivacyClass::CircuitDerived),
    ("ui.error_observed", FeedbackPrivacyClass::Operational),
    ("recommendation.shown", FeedbackPrivacyClass::Operational),
    ("recommendation.outcome", FeedbackPrivacyClass::Operational),
    ("user.feedback_submitted", FeedbackPrivacyClass::UserContent),
    (
        "validation.case_completed",
        FeedbackPrivacyClass::CircuitDerived,
    ),
    ("export.created", FeedbackPrivacyClass::Operational),
    ("data.deleted", FeedbackPrivacyClass::Operational),
];
