import type { SParameterResult } from "./mcu-types";

function formatComplex(
  value: { re: number; im: number },
  format: "MA" | "RI",
): string {
  if (format === "MA") {
    const magnitude = Math.hypot(value.re, value.im);
    const angle = Math.atan2(value.im, value.re) * (180 / Math.PI);
    return `${magnitude.toExponential(6)} ${angle.toFixed(3)}`;
  }
  return `${value.re.toExponential(6)} ${value.im.toExponential(6)}`;
}

export function formatTouchstone(
  result: SParameterResult,
  generatedAt = new Date(),
): string {
  const portCount = result.sMatrices[0]?.length ?? 0;
  if (portCount === 0 || result.frequencies.length !== result.sMatrices.length) return "";

  const format = result.format === "ma" ? "MA" : "RI";
  const lines = [
    "! Touchstone file generated by Astryd Sophia",
    `! S-Parameter Matrix: ${portCount}-port`,
    `! Date: ${generatedAt.toISOString()}`,
    `! Reference impedance: ${result.referenceImpedance} ohm`,
    `# Hz S ${format} R ${result.referenceImpedance}`,
  ];

  for (let frequencyIndex = 0; frequencyIndex < result.frequencies.length; frequencyIndex += 1) {
    const frequency = result.frequencies[frequencyIndex];
    const matrix = result.sMatrices[frequencyIndex];
    if (matrix.length !== portCount || matrix.some(row => row.length !== portCount)) return "";

    if (portCount <= 2) {
      const values: string[] = [];
      // Touchstone 1.x/2.0 mantiene orden por excitacion: S11, S21, S12, S22.
      for (let inputPort = 0; inputPort < portCount; inputPort += 1) {
        for (let outputPort = 0; outputPort < portCount; outputPort += 1) {
          values.push(formatComplex(matrix[outputPort][inputPort], format));
        }
      }
      lines.push(`${frequency.toExponential(6)}  ${values.join("  ")}`);
      continue;
    }

    // Para N >= 3, Touchstone representa una fila de matriz por linea.
    for (let outputPort = 0; outputPort < portCount; outputPort += 1) {
      const values = matrix[outputPort].map(value => formatComplex(value, format));
      const prefix = outputPort === 0 ? frequency.toExponential(6) : "  ";
      lines.push(`${prefix}  ${values.join("  ")}`);
    }
  }

  lines.push("");
  return lines.join("\n");
}
