import type { AcSweepResult, TimeStepResult } from "./oscilloscope_panel";
import type { AnalysisMode } from "./simulation_controls";

export interface ExportSnapshot {
  activeAnalysisMode: AnalysisMode;
  acResults: AcSweepResult | null;
  transientResults: readonly TimeStepResult[];
  ch1Node: string | null;
  ch2Node: string | null;
  voltageMap: Record<string, number>;
}

export interface TextExport {
  filename: string;
  content: string;
}

const CH1_COLOR = "hsl(174, 97%, 69%)";
const CH2_COLOR = "hsl(270, 89%, 65%)";

export function buildCsvExport(snapshot: ExportSnapshot): TextExport {
  const { activeAnalysisMode, acResults, transientResults, ch1Node, ch2Node, voltageMap } = snapshot;

  if (activeAnalysisMode === "AC" && acResults !== null) {
    let content = "Frecuencia (Hz),Magnitud Canal 1 (dB),Fase Canal 1 (Grados),Magnitud Canal 2 (dB),Fase Canal 2 (Grados)\n";
    const freqs = acResults.frequencies;
    for (let i = 0; i < freqs.length; i++) {
      const f = freqs[i];
      const db1 = ch1Node ? acResults.nodeAmplitudes[ch1Node]?.[i] ?? 0.0 : 0.0;
      const ph1 = ch1Node ? acResults.nodePhases[ch1Node]?.[i] ?? 0.0 : 0.0;
      const db2 = ch2Node ? acResults.nodeAmplitudes[ch2Node]?.[i] ?? 0.0 : 0.0;
      const ph2 = ch2Node ? acResults.nodePhases[ch2Node]?.[i] ?? 0.0 : 0.0;
      content += `${f.toFixed(2)},${db1.toFixed(4)},${ph1.toFixed(4)},${db2.toFixed(4)},${ph2.toFixed(4)}\n`;
    }
    return { filename: "reporte_barrido_ca.csv", content };
  }

  if ((activeAnalysisMode === "TRAN" || activeAnalysisMode === "PSS") && transientResults.length > 0) {
    let content = "Tiempo (s),Voltaje Canal 1 (V),Voltaje Canal 2 (V)\n";
    transientResults.forEach((pt) => {
      const v1 = ch1Node ? pt.nodeVoltages[ch1Node] ?? 0.0 : 0.0;
      const v2 = ch2Node ? pt.nodeVoltages[ch2Node] ?? 0.0 : 0.0;
      content += `${pt.time.toFixed(6)},${v1.toFixed(5)},${v2.toFixed(5)}\n`;
    });
    return { filename: "reporte_transitorio.csv", content };
  }

  let content = "Nodo,Voltaje Operacion (V)\n";
  for (const [node, volt] of Object.entries(voltageMap)) {
    content += `${node},${volt.toFixed(5)}\n`;
  }
  return { filename: "reporte_punto_operacion_cc.csv", content };
}

export function buildTouchstoneExport(snapshot: ExportSnapshot, createdAtIso: string): TextExport | null {
  const { activeAnalysisMode, acResults, ch1Node, ch2Node } = snapshot;
  if (activeAnalysisMode !== "AC" || !acResults || acResults.frequencies.length === 0) {
    return null;
  }

  let content = "! Touchstone 2-Port File generated by Astryd Sophia v2.0 Evolution\n";
  content += `! Created on: ${createdAtIso}\n`;
  content += `! Source nodes: Port 1 = Node ${ch1Node ?? "N/A"}, Port 2 = Node ${ch2Node ?? "N/A"}\n`;
  content += "# Hz S DB R 50\n";

  const freqs = acResults.frequencies;
  for (let i = 0; i < freqs.length; i++) {
    const f = freqs[i];
    const s11Db = ch1Node ? acResults.nodeAmplitudes[ch1Node]?.[i] ?? -80.0 : -80.0;
    const s11Phase = ch1Node ? acResults.nodePhases[ch1Node]?.[i] ?? 0.0 : 0.0;
    const s21Db = ch2Node ? acResults.nodeAmplitudes[ch2Node]?.[i] ?? -80.0 : -80.0;
    const s21Phase = ch2Node ? acResults.nodePhases[ch2Node]?.[i] ?? 0.0 : 0.0;

    content += `${f.toFixed(4)} ${s11Db.toFixed(6)} ${s11Phase.toFixed(6)} ${s21Db.toFixed(6)} ${s21Phase.toFixed(6)} -80.000000 0.000000 -80.000000 0.000000\n`;
  }

  return { filename: "reporte_s2p.s2p", content };
}

export function buildSvgExport(snapshot: ExportSnapshot): TextExport {
  const { activeAnalysisMode, acResults, transientResults, ch1Node, ch2Node } = snapshot;
  let content = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 400" style="background:#030508; font-family:sans-serif;">`;
  let filename = "grafico_simulacion.svg";

  content += `<rect width="800" height="400" fill="#030508" />`;
  content += `<text x="400" y="25" fill="${CH1_COLOR}" font-size="16" font-weight="bold" text-anchor="middle">Astryd Sophia v2.0 Evolution - Reporte Grafico</text>`;

  if (activeAnalysisMode === "AC" && acResults !== null && acResults.frequencies.length > 0) {
    filename = "grafico_barrido_ca.svg";
    content += buildPlotAxes();
    if (ch1Node) content += buildBodePath(acResults, ch1Node, CH1_COLOR, "Magnitud CH1", ch1Node);
    if (ch2Node) content += buildBodePath(acResults, ch2Node, CH2_COLOR, "Magnitud CH2", ch1Node);
  } else if ((activeAnalysisMode === "TRAN" || activeAnalysisMode === "PSS") && transientResults.length > 0) {
    filename = "grafico_transitorio.svg";
    content += buildPlotAxes();
    if (ch1Node) content += buildTransientPath(transientResults, ch1Node, CH1_COLOR, "Voltaje CH1", ch1Node);
    if (ch2Node) content += buildTransientPath(transientResults, ch2Node, CH2_COLOR, "Voltaje CH2", ch1Node);
  } else {
    content += `<text x="400" y="200" fill="#64748b" font-size="14" text-anchor="middle">No hay curvas transitorias o de CA para exportar en este modo.</text>`;
  }

  content += "</svg>";
  return { filename, content };
}

function buildPlotAxes(): string {
  return `<line x1="50" y1="350" x2="750" y2="350" stroke="#1e293b" stroke-width="1.5" />`
    + `<line x1="50" y1="50" x2="50" y2="350" stroke="#1e293b" stroke-width="1.5" />`;
}

function buildBodePath(
  acResults: AcSweepResult,
  node: string,
  color: string,
  name: string,
  ch1Node: string | null,
): string {
  const amps = acResults.nodeAmplitudes[node];
  if (!amps) return "";
  const freqs = acResults.frequencies;
  const fMin = freqs[0];
  const fMax = freqs[freqs.length - 1];
  const logSpan = Math.log10(fMax) - Math.log10(fMin) || 1;

  let path = "";
  for (let i = 0; i < freqs.length; i++) {
    const ratio = (Math.log10(freqs[i]) - Math.log10(fMin)) / logSpan;
    const x = 50 + ratio * 700;
    const dbVal = Math.max(-60, Math.min(10, amps[i]));
    const y = 350 - ((dbVal + 60) / 70) * 300;
    path += `${i === 0 ? "M" : "L"} ${x.toFixed(1)} ${y.toFixed(1)} `;
  }
  return `<path d="${path}" fill="none" stroke="${color}" stroke-width="2.5" /><text x="60" y="${node === ch1Node ? "70" : "90"}" fill="${color}" font-size="11" font-weight="bold">${name} (${node})</text>`;
}

function buildTransientPath(
  transientResults: readonly TimeStepResult[],
  node: string,
  color: string,
  name: string,
  ch1Node: string | null,
): string {
  const tMax = transientResults[transientResults.length - 1].time || 1;
  let minV = 0.0;
  let maxV = 1.0;
  transientResults.forEach((pt) => {
    const v = pt.nodeVoltages[node] ?? 0.0;
    if (v < minV) minV = v;
    if (v > maxV) maxV = v;
  });
  const vDiff = maxV - minV || 1.0;

  let path = "";
  for (let i = 0; i < transientResults.length; i++) {
    const pt = transientResults[i];
    const x = 50 + (pt.time / tMax) * 700;
    const v = pt.nodeVoltages[node] ?? 0.0;
    const y = 350 - ((v - minV) / vDiff) * 300;
    path += `${i === 0 ? "M" : "L"} ${x.toFixed(1)} ${y.toFixed(1)} `;
  }
  return `<path d="${path}" fill="none" stroke="${color}" stroke-width="2.5" /><text x="60" y="${node === ch1Node ? "70" : "90"}" fill="${color}" font-size="11" font-weight="bold">${name} (${node})</text>`;
}
