// ==========================================================================
// COMPONENT CATALOG MODEL — Catálogo reactivo y metadatos EDA enriquecidos
// ==========================================================================

import type { ComponentCategory } from "./types";
import type { ComponentInstance } from "../canvas_orchestrator";

export type SymbolStandard = "IEEE" | "IEC";
export type PaletteViewMode = "grid" | "list";

export interface EnhancedCatalogItem {
  readonly id: string;
  readonly type: ComponentInstance["type"];
  readonly name: string;
  readonly shortName: string;
  readonly category: ComponentCategory;
  readonly categoryLabel: string;
  readonly description: string;
  readonly defaultVal: string | number;
  readonly unit: string;
  readonly hotkey?: string;
  readonly physicsEquation?: string;
  readonly academicSummary?: string;
  readonly spiceModelLevel?: string;
  readonly commercialSeries?: readonly string[];
  readonly packageFootprint?: string;
  readonly tags: readonly string[];
  readonly isExperimental?: boolean;
  readonly isNonLinear?: boolean;
  readonly hasActiveBehavior?: boolean;
  readonly svgIconIeee: string;
  readonly svgIconIec: string;
  readonly extraProps?: {
    readonly modelName?: string;
    readonly pinCount?: number;
    readonly pinLabels?: Record<number, string>;
    readonly spiceNetlist?: string;
    readonly terminalType?: string;
  };
}

export interface CategoryGroupMeta {
  readonly id: ComponentCategory;
  readonly name: string;
  readonly icon: string;
  readonly colorAccent: string;
}

export const CATEGORY_METAS: readonly CategoryGroupMeta[] = [
  { id: "pasivos", name: "Pasivos y Filtros", icon: "⚡", colorAccent: "#A78BFA" },
  { id: "semiconductores", name: "Semiconductores y Diodos", icon: "⏆", colorAccent: "#38BDF8" },
  { id: "analogicos", name: "Fuentes y Analógica", icon: "📈", colorAccent: "#34D399" },
  { id: "actuadores", name: "Actuadores y Switches", icon: "💡", colorAccent: "#F59E0B" },
  { id: "logica-digital", name: "Lógica Digital (Gates)", icon: "⎍", colorAccent: "#EC4899" },
  { id: "digitales-mcus", name: "Microcontroladores y SoCs", icon: "🖳", colorAccent: "#818CF8" },
  { id: "anotaciones", name: "Puertos, Rieles y Documentación", icon: "🏷️", colorAccent: "#FBBF24" },
  { id: "macromodelos", name: "Macromodelos SPICE (.SUBCKT)", icon: "📦", colorAccent: "#06B6D4" },
];

export const FAVORITE_COMPONENT_IDS: readonly string[] = [
  "ground",
  "vsource",
  "resistor",
  "capacitor",
  "inductor",
  "diode",
  "npn",
  "opamp_ideal",
  "switch",
  "net_label",
];

export const COMPONENT_CATALOG: readonly EnhancedCatalogItem[] = [
  // ─── PASIVOS ──────────────────────────────────────────────────────────
  {
    id: "resistor",
    type: "resistor",
    name: "Resistencia",
    shortName: "R",
    category: "pasivos",
    categoryLabel: "Pasivos",
    description: "Resistencia eléctrica pasiva. Limita y polariza corriente.",
    defaultVal: "1000",
    unit: "Ω",
    hotkey: "R",
    physicsEquation: "V = I · R  (P = I² · R)",
    academicSummary: "Elemento lineal que disipa energía en calor conforme a la Ley de Ohm y efecto Joule.",
    spiceModelLevel: "R (Discreto Lineal con ESL/Cp parásitos y TC1/TC2)",
    commercialSeries: ["E12", "E24", "E96"],
    packageFootprint: "0805 / Axial",
    tags: ["resistencia", "resistor", "ohm", "pasivo", "r", "1k", "divider", "divisor", "potencia"],
    svgIconIeee: `<path d="M 4 20 L 10 20 L 13 12 L 18 28 L 22 12 L 27 28 L 30 20 L 36 20" />`,
    svgIconIec: `<path d="M 4 20 L 10 20 M 30 20 L 36 20" /><rect x="10" y="13" width="20" height="14" rx="1" fill="currentColor" fill-opacity="0.15" />`,
  },
  {
    id: "capacitor",
    type: "capacitor",
    name: "Condensador",
    shortName: "C",
    category: "pasivos",
    categoryLabel: "Pasivos",
    description: "Almacenamiento de carga en campo electrostático.",
    defaultVal: "0.000001",
    unit: "F",
    hotkey: "C",
    physicsEquation: "I(t) = C · dV(t)/dt  (E = ½ C V²)",
    academicSummary: "Componente dinámico que se opone a cambios bruscos de tensión. Modela filtrado y desacoplo.",
    spiceModelLevel: "C (Lineal Transitorio con ESR, ESL y Rleak parásitos)",
    commercialSeries: ["E12", "E24"],
    packageFootprint: "0805 / Radial",
    tags: ["condensador", "capacitor", "faradio", "cap", "filtro", "c", "1u", "desacoplo", "ceramico", "electrolitico"],
    svgIconIeee: `<path d="M 4 20 L 15 20 M 25 20 L 36 20 M 15 8 L 15 32 M 25 8 Q 23 20 25 32" />`,
    svgIconIec: `<path d="M 4 20 L 15 20 M 25 20 L 36 20 M 15 8 L 15 32 M 25 8 L 25 32" />`,
  },
  {
    id: "inductor",
    type: "inductor",
    name: "Bobina / Inductor",
    shortName: "L",
    category: "pasivos",
    categoryLabel: "Pasivos",
    description: "Almacenamiento de energía en campo magnético.",
    defaultVal: "0.001",
    unit: "H",
    hotkey: "L",
    physicsEquation: "V(t) = L · dI(t)/dt  (E = ½ L I²)",
    academicSummary: "Se opone a variaciones abruptas de corriente. Fundamental en fuentes conmutadas y filtros LC.",
    spiceModelLevel: "L (Lineal Transitorio con DCR serie y Cp paralelo)",
    commercialSeries: ["E12"],
    packageFootprint: "Radial / SMD Power",
    tags: ["inductor", "bobina", "henrio", "l", "choke", "filtro", "magnetico", "reactancia"],
    svgIconIeee: `<path d="M 4 20 C 4 10, 12 10, 12 20 C 12 10, 20 10, 20 20 C 20 10, 28 10, 28 20 C 28 10, 36 10, 36 20" />`,
    svgIconIec: `<path d="M 4 20 L 10 20 M 30 20 L 36 20" /><rect x="10" y="14" width="20" height="12" fill="currentColor" />`,
  },
  {
    id: "potentiometer",
    type: "potentiometer",
    name: "Potenciómetro",
    shortName: "POT",
    category: "pasivos",
    categoryLabel: "Pasivos",
    description: "Resistencia variable con cursor / divisor de tensión.",
    defaultVal: "10000",
    unit: "Ω",
    physicsEquation: "R₁₂ = k · R_tot, R₂₃ = (1-k) · R_tot",
    academicSummary: "Ajuste continuo de ganancia o atenuación mediante cursor móvil interactivo.",
    spiceModelLevel: "Subcircuito divisor dual paramétrico",
    commercialSeries: ["1k", "10k", "50k", "100k"],
    tags: ["potenciometro", "pot", "variable", "reostato", "divisor", "trimmer", "ajustable"],
    svgIconIeee: `<path d="M 4 20 L 10 20 L 13 12 L 18 28 L 22 12 L 27 28 L 30 20 L 36 20 M 20 36 L 20 28 L 17 25" />`,
    svgIconIec: `<path d="M 4 20 L 10 20 M 30 20 L 36 20 M 10 13 H 30 V 27 H 10 Z M 20 36 L 20 27" /><polygon points="18,27 20,22 22,27" fill="currentColor" />`,
  },
  {
    id: "ldr",
    type: "ldr",
    name: "Fotoresistencia (LDR)",
    shortName: "LDR",
    category: "pasivos",
    categoryLabel: "Pasivos",
    description: "Sensor óptico cuya resistencia disminuye con la luz.",
    defaultVal: "100",
    unit: "Lux",
    physicsEquation: "R(Lux) = R₀ · (Lux)^(-γ)",
    academicSummary: "Material semiconductor fotosensible (CdS). Modela transducción luz-resistencia.",
    spiceModelLevel: "Modelo no lineal paramétrico con fotocorriente",
    tags: ["fotorresistencia", "luz", "sensor", "ldr", "optico", "foto", "fotocelda", "lux"],
    svgIconIeee: `<circle cx="20" cy="20" r="13" /><path d="M 11 20 L 14 20 L 16 17 L 18 23 L 20 17 L 22 23 L 24 20 L 29 20" /><path d="M 8 8 L 13 13 M 12 8 L 16 12" />`,
    svgIconIec: `<circle cx="20" cy="20" r="13" /><rect x="12" y="15" width="16" height="10" fill="currentColor" fill-opacity="0.15" /><path d="M 8 8 L 13 13 M 12 8 L 16 12" />`,
  },
  {
    id: "thermistor",
    type: "thermistor",
    name: "Termistor (NTC)",
    shortName: "NTC",
    category: "pasivos",
    categoryLabel: "Pasivos",
    description: "Sensor de temperatura con coeficiente térmico negativo.",
    defaultVal: "25",
    unit: "°C",
    physicsEquation: "R(T) = R₀ · exp[β · (1/T - 1/T₀)]",
    academicSummary: "Transductor térmico de alta sensibilidad según ecuación de Steinhart-Hart.",
    spiceModelLevel: "NTC Termo-resistivo no lineal",
    tags: ["termistor", "temperatura", "sensor", "ntc", "ptc", "termico", "grados", "calor"],
    svgIconIeee: `<path d="M 4 20 L 10 20 L 13 12 L 18 28 L 22 12 L 27 28 L 30 20 L 36 20 M 10 32 L 13 32 L 28 8" />`,
    svgIconIec: `<rect x="10" y="14" width="20" height="12" rx="1" fill="currentColor" fill-opacity="0.15" /><path d="M 4 20 L 10 20 M 30 20 L 36 20 M 10 32 L 13 32 L 28 8" />`,
  },
  {
    id: "fuse",
    type: "fuse",
    name: "Fusible Térmico",
    shortName: "FUSE",
    category: "pasivos",
    categoryLabel: "Pasivos",
    description: "Protección contra sobrecorrientes por fusión térmica I²t.",
    defaultVal: "1.0",
    unit: "A",
    physicsEquation: "∫ I²(t) dt ≥ I²t_fusión",
    academicSummary: "Elemento de sacrificio de seguridad eléctrica con curva de desconexión transitoria.",
    spiceModelLevel: "Interruptor térmico de estado persistente",
    tags: ["fusible", "fuse", "proteccion", "sobrecorriente", "seguridad", "corte"],
    svgIconIeee: `<path d="M 4 20 L 10 20 M 30 20 L 36 20 M 10 20 C 14 12, 16 28, 20 20 C 24 12, 26 28, 30 20" />`,
    svgIconIec: `<rect x="10" y="14" width="20" height="12" rx="1" fill="currentColor" fill-opacity="0.15" /><path d="M 4 20 L 36 20" />`,
  },
  {
    id: "ground",
    type: "ground",
    name: "Tierra de Referencia (GND)",
    shortName: "GND",
    category: "pasivos",
    categoryLabel: "Pasivos",
    description: "Nodo de potencial cero absoluto (0 V).",
    defaultVal: "0",
    unit: "V",
    hotkey: "G",
    physicsEquation: "V_GND ≡ 0.000 V",
    academicSummary: "Nodo de referencia matemático de la formulación MNA (Fila/Columna eliminada del sistema).",
    spiceModelLevel: "Nodo 0 de SPICE",
    tags: ["tierra", "gnd", "ground", "0v", "referencia", "masa", "cero", "nodo 0"],
    svgIconIeee: `<path d="M 20 6 L 20 20 M 8 20 L 32 20 M 13 27 L 27 27 M 18 34 L 22 34" />`,
    svgIconIec: `<path d="M 20 6 L 20 20 M 8 20 L 32 20 M 13 27 L 27 27 M 18 34 L 22 34" />`,
  },
  {
    id: "transformer",
    type: "transformer",
    name: "Transformador",
    shortName: "TRAFO",
    category: "pasivos",
    categoryLabel: "Pasivos",
    description: "Acoplamiento magnético mutuo con relación de vueltas N₁:N₂.",
    defaultVal: "0.001",
    unit: "H/k",
    physicsEquation: "V₂/V₁ = N₂/N₁ = √(L₂/L₁),  k ≤ 1.0",
    academicSummary: "Conversión de tensión/corriente CA mediante inductancia mutua M = k√(L₁ L₂).",
    spiceModelLevel: "K (Mutual Inductor SPICE)",
    tags: ["transformador", "trafo", "bobinado", "ac", "relacion vueltas", "aislacion"],
    svgIconIeee: `<path d="M 6 12 C 6 8, 12 8, 12 12 C 12 8, 18 8, 18 12 C 18 8, 24 8, 24 12 C 24 8, 30 8, 30 12 M 12 18 L 12 22 M 24 18 L 24 22" /><circle cx="9" cy="12" r="2" fill="currentColor" /><circle cx="27" cy="12" r="2" fill="currentColor" />`,
    svgIconIec: `<rect x="6" y="10" width="12" height="20" rx="1" fill="currentColor" fill-opacity="0.1" /><rect x="22" y="10" width="12" height="20" rx="1" fill="currentColor" fill-opacity="0.1" /><path d="M 19 8 L 19 32 M 21 8 L 21 32" />`,
  },
  {
    id: "dmm",
    type: "dmm",
    name: "Multímetro Digital (DMM)",
    shortName: "DMM",
    category: "pasivos",
    categoryLabel: "Pasivos",
    description: "Instrumento virtual para medición de Voltios, Amperios y Ohmios.",
    defaultVal: "V",
    unit: "MTR",
    academicSummary: "Muestra magnitudes RMS, pico y continua calculadas dinámicamente sobre la simulación.",
    spiceModelLevel: "Medidor de alta impedancia (10 MΩ en V) o shunt (0 Ω en I)",
    tags: ["multimetro", "dmm", "tester", "voltimetro", "amperimetro", "ohmetro", "medidor"],
    svgIconIeee: `<rect x="8" y="4" width="24" height="32" rx="3" /><rect x="12" y="8" width="16" height="10" rx="1" fill="currentColor" fill-opacity="0.15" /><circle cx="20" cy="26" r="4" /><path d="M 20 26 L 20 23" />`,
    svgIconIec: `<circle cx="20" cy="20" r="14" /><text x="20" y="24" text-anchor="middle" font-size="12" font-weight="bold" fill="currentColor">V/A</text>`,
  },
  {
    id: "wattmeter",
    type: "wattmeter",
    name: "Vatímetro / Analizador de Potencia",
    shortName: "WATT",
    category: "pasivos",
    categoryLabel: "Instrumentación",
    description: "Medidor simultáneo de potencia activa (W), aparente (VA) y factor de potencia (PF).",
    defaultVal: "0",
    unit: "W",
    physicsEquation: "P = \\frac{1}{T}\\int_0^T v(t) i(t) \\, dt, \\quad PF = \\frac{P}{S}",
    academicSummary: "Analizador de 4 terminales para circuitos de CC y CA monofásicos con cálculo instantáneo y RMS.",
    spiceModelLevel: "Medidor dual tensión/corriente con shunt de 1 mΩ",
    tags: ["vatimetro", "wattmeter", "potencia", "factor de potencia", "cos phi", "vatios", "medidor"],
    svgIconIeee: `<rect x="6" y="6" width="28" height="28" rx="3" /><rect x="10" y="10" width="20" height="10" rx="1" fill="currentColor" fill-opacity="0.15" /><text x="20" y="30" text-anchor="middle" font-size="9" font-weight="bold" fill="currentColor">W</text>`,
    svgIconIec: `<circle cx="20" cy="20" r="14" /><text x="20" y="24" text-anchor="middle" font-size="12" font-weight="bold" fill="currentColor">W</text>`,
  },
  {
    id: "frequency_counter",
    type: "frequency_counter",
    name: "Frecuencímetro / Contador Digital",
    shortName: "FREQ",
    category: "pasivos",
    categoryLabel: "Instrumentación",
    description: "Instrumento de banco para medición de frecuencia, periodo y ciclo de trabajo en tiempo real.",
    defaultVal: "1000",
    unit: "Hz",
    physicsEquation: "f = \\frac{1}{T}, \\quad D = \\frac{T_{on}}{T} \\cdot 100\\%",
    academicSummary: "Lectura digital precisa de frecuencia de 0 Hz a 1 GHz con detección de cruce por cero.",
    spiceModelLevel: "Contador de alta impedancia (10 MΩ)",
    tags: ["frecuencimetro", "frequency counter", "contador", "frecuencia", "periodo", "tacometro", "medidor"],
    svgIconIeee: `<rect x="4" y="8" width="32" height="24" rx="2" /><rect x="8" y="12" width="24" height="10" rx="1" fill="currentColor" fill-opacity="0.15" /><text x="20" y="29" text-anchor="middle" font-size="7" font-weight="bold" fill="currentColor">Hz</text>`,
    svgIconIec: `<rect x="4" y="8" width="32" height="24" rx="2" /><rect x="8" y="12" width="24" height="10" rx="1" fill="currentColor" fill-opacity="0.15" /><text x="20" y="29" text-anchor="middle" font-size="7" font-weight="bold" fill="currentColor">Hz</text>`,
  },
  {
    id: "logic_probe",
    type: "logic_probe",
    name: "Sonda Lógica Digital",
    shortName: "SONDA",
    category: "logica-digital",
    categoryLabel: "Instrumentación",
    description: "Punta de prueba digital con indicador LED tricolor para HIGH (1), LOW (0) y Hi-Z (X).",
    defaultVal: "X",
    unit: "LOGIC",
    physicsEquation: "V_{IN} \\ge 2.0\\,\\text{V} \\implies 1, \\quad V_{IN} \\le 0.8\\,\\text{V} \\implies 0",
    academicSummary: "Diagnóstico instantáneo de estados lógicos TTL/CMOS sin sobrecargar el nodo de prueba.",
    spiceModelLevel: "Sensor de alta impedancia (10 MΩ)",
    hasActiveBehavior: true,
    tags: ["sonda logica", "logic probe", "punta de prueba", "high", "low", "tri-state", "digital", "ttl", "cmos"],
    svgIconIeee: `<path d="M 20 36 L 20 24 M 14 24 L 26 24 L 26 6 L 14 6 Z M 20 12 L 20 18" /><circle cx="20" cy="15" r="3" fill="currentColor" />`,
    svgIconIec: `<path d="M 20 36 L 20 24 M 14 24 L 26 24 L 26 6 L 14 6 Z M 20 12 L 20 18" /><circle cx="20" cy="15" r="3" fill="currentColor" />`,
  },
  {
    id: "pulse_generator",
    type: "pulse_generator",
    name: "Inyector de Pulsos Lógicos",
    shortName: "PULSER",
    category: "logica-digital",
    categoryLabel: "Instrumentación",
    description: "Generador portátil de pulsos e inyector para excitación de circuitos lógicos y secuenciales.",
    defaultVal: "1000",
    unit: "Hz",
    physicsEquation: "V_{OUT} = 5.0\\,\\text{V}, \\quad f = 1\\,\\text{kHz}",
    academicSummary: "Inyecta pulsos manuales únicos o tren continuo de reloj para probar flip-flops y registros.",
    spiceModelLevel: "Generador de pulsos de baja impedancia (25 Ω)",
    hasActiveBehavior: true,
    tags: ["inyector de pulsos", "pulse generator", "pulser", "reloj", "clock", "disparo", "generador"],
    svgIconIeee: `<rect x="10" y="6" width="20" height="28" rx="3" /><circle cx="20" cy="14" r="4" fill="currentColor" /><path d="M 14 26 L 17 26 L 17 22 L 23 22 L 23 26 L 26 26" stroke="currentColor" stroke-width="1.5" />`,
    svgIconIec: `<rect x="10" y="6" width="20" height="28" rx="3" /><circle cx="20" cy="14" r="4" fill="currentColor" /><path d="M 14 26 L 17 26 L 17 22 L 23 22 L 23 26 L 26 26" stroke="currentColor" stroke-width="1.5" />`,
  },

  // ─── SEMICONDUCTORES ──────────────────────────────────────────────────
  {
    id: "diode",
    type: "diode",
    name: "Diodo Rectificador PN",
    shortName: "D",
    category: "semiconductores",
    categoryLabel: "Semiconductores",
    description: "Conducción unidireccional no lineal con umbral de silicio (~0.7V).",
    defaultVal: "0",
    unit: "PN",
    hotkey: "D",
    physicsEquation: "I_D = I_S · (exp(q V_D / η k T) - 1)",
    academicSummary: "Resuelto mediante iteración Newton-Raphson de la ecuación de Shockley en el solver MNA.",
    spiceModelLevel: "D (Shockley con RS, CJ0, BV, IBV y TT)",
    isNonLinear: true,
    commercialSeries: ["1N4007", "1N4148"],
    tags: ["diodo", "rectificador", "pn", "silicio", "schottky", "zener", "conduccion"],
    svgIconIeee: `<path d="M 4 20 L 14 20 M 26 20 L 36 20 M 14 10 L 26 20 L 14 30 Z M 26 10 L 26 30" />`,
    svgIconIec: `<path d="M 4 20 L 14 20 M 26 20 L 36 20 M 14 10 L 26 20 L 14 30 Z M 26 10 L 26 30" />`,
  },
  {
    id: "zener_diode",
    type: "zener_diode",
    name: "Diodo Zener",
    shortName: "ZENER",
    category: "semiconductores",
    categoryLabel: "Semiconductores",
    description: "Regulador de tensión por avalancha/efecto Zener en polarización inversa.",
    defaultVal: "5.1",
    unit: "V",
    physicsEquation: "V_zener = V_Z + I_Z · r_Z  (I_Z > I_ZK)",
    academicSummary: "Mantiene una tensión constante y estable en inversa para referencias y protecciones.",
    spiceModelLevel: "D con tensión de ruptura BV y resistencia zener",
    isNonLinear: true,
    commercialSeries: ["BZX55C (5.1V)", "1N4733A"],
    tags: ["zener", "regulador", "referencia", "avalancha", "diodo zener"],
    svgIconIeee: `<path d="M 4 20 L 14 20 M 26 20 L 36 20 M 14 10 L 26 20 L 14 30 Z M 26 10 L 26 30 M 26 10 L 23 7 M 26 30 L 29 33" />`,
    svgIconIec: `<path d="M 4 20 L 14 20 M 26 20 L 36 20 M 14 10 L 26 20 L 14 30 Z M 26 10 L 26 30 M 26 10 L 23 10 M 26 30 L 29 30" />`,
  },
  {
    id: "schottky_diode",
    type: "schottky_diode",
    name: "Diodo Schottky",
    shortName: "SCHOTTKY",
    category: "semiconductores",
    categoryLabel: "Semiconductores",
    description: "Conmutación ultrarrápida y baja caída directa (~0.2V a 0.3V).",
    defaultVal: "0",
    unit: "V",
    physicsEquation: "V_F ≈ 0.25 V,  t_rr ≈ 0 ns",
    academicSummary: "Unión metal-semiconductor ideal para rectificación de alta frecuencia y fuentes SMPS.",
    spiceModelLevel: "Diodo de baja barrera con TT reducido",
    isNonLinear: true,
    commercialSeries: ["BAT54", "1N5819"],
    tags: ["schottky", "rapido", "baja caida", "smps", "conmutacion"],
    svgIconIeee: `<path d="M 4 20 L 14 20 M 26 20 L 36 20 M 14 10 L 26 20 L 14 30 Z M 26 10 L 26 30 M 26 10 L 23 10 L 23 13 M 26 30 L 29 30 L 29 27" />`,
    svgIconIec: `<path d="M 4 20 L 14 20 M 26 20 L 36 20 M 14 10 L 26 20 L 14 30 Z M 26 10 L 26 30 M 26 10 L 23 10 M 26 30 L 29 30" />`,
  },
  {
    id: "led",
    type: "led",
    name: "Diodo LED",
    shortName: "LED",
    category: "semiconductores",
    categoryLabel: "Semiconductores",
    description: "Emisión de luz por recombinación radiativa de portadores.",
    defaultVal: "0",
    unit: "RGB",
    physicsEquation: "h ν = E_g,  Brillo ∝ I_F",
    academicSummary: "Diodo optoelectrónico con renderizado dinámico de luminosidad y color según corriente.",
    spiceModelLevel: "Diodo no lineal con emisión fotónica",
    isNonLinear: true,
    hasActiveBehavior: true,
    tags: ["diodo emisor de luz", "led", "iluminacion", "diodo", "luz", "rojo", "verde", "azul"],
    svgIconIeee: `<path d="M 4 20 L 14 20 M 26 20 L 36 20 M 14 10 L 26 20 L 14 30 Z M 26 10 L 26 30 M 28 14 L 33 9 M 28 14 L 35 14 M 28 26 L 33 31 M 28 26 L 35 26" />`,
    svgIconIec: `<path d="M 4 20 L 14 20 M 26 20 L 36 20 M 14 10 L 26 20 L 14 30 Z M 26 10 L 26 30 M 28 14 L 33 9 M 28 14 L 35 14" />`,
  },
  {
    id: "scr",
    type: "scr",
    name: "Tiristor SCR (2N5064 / BT151)",
    shortName: "SCR",
    category: "semiconductores",
    categoryLabel: "Semiconductores",
    description: "Rectificador controlado de silicio con enclavamiento por pulso de compuerta.",
    defaultVal: "0",
    unit: "SCR",
    physicsEquation: "I_{AK} > I_H \\implies \\text{Enclavado ON}, \\quad V_{GK} \\ge V_{GT}",
    academicSummary: "Interruptor unidireccional de potencia retenido en conducción hasta conmutación por cero.",
    spiceModelLevel: "Macromodelo SCR dos transistores complementarios",
    isNonLinear: true,
    hasActiveBehavior: true,
    commercialSeries: ["2N5064", "BT151", "TIC106", "C106D"],
    packageFootprint: "TO-92 / TO-220",
    tags: ["tiristor", "scr", "rectificador controlado", "2n5064", "bt151", "tic106", "potencia", "disparo puerta"],
    svgIconIeee: `<path d="M 20 4 L 20 14 M 20 26 L 20 36 M 10 14 L 30 14 L 20 26 Z M 10 26 L 30 26 M 20 26 L 12 34 L 6 34" fill="currentColor" fill-opacity="0.1" />`,
    svgIconIec: `<path d="M 20 4 L 20 14 M 20 26 L 20 36 M 10 14 L 30 14 L 20 26 Z M 10 26 L 30 26 M 20 26 L 12 34 L 6 34" fill="currentColor" fill-opacity="0.1" />`,
  },
  {
    id: "triac",
    type: "triac",
    name: "Triac (BT136 / BTA16)",
    shortName: "TRIAC",
    category: "semiconductores",
    categoryLabel: "Semiconductores",
    description: "Interruptor bidireccional de corriente alterna con disparo en 4 cuadrantes.",
    defaultVal: "0",
    unit: "TRIAC",
    physicsEquation: "|I_{MT}| > I_H \\implies \\text{Conducción bidireccional}",
    academicSummary: "Control de ángulo de fase de onda completa para dimmers y control de motores CA.",
    spiceModelLevel: "Macromodelo Triac antiparalelo",
    isNonLinear: true,
    hasActiveBehavior: true,
    commercialSeries: ["BT136", "BT138", "BTA16", "MAC97A6"],
    packageFootprint: "TO-220 / TO-92",
    tags: ["triac", "bt136", "bta16", "dimmer", "control ca", "fase", "potencia", "bidireccional"],
    svgIconIeee: `<path d="M 20 4 L 20 14 M 20 26 L 20 36 M 10 14 L 25 14 L 14 26 Z M 27 14 L 16 26 L 30 26 Z M 10 14 L 30 14 M 10 26 L 30 26 M 20 26 L 12 34 L 6 34" fill="currentColor" fill-opacity="0.1" />`,
    svgIconIec: `<path d="M 20 4 L 20 14 M 20 26 L 20 36 M 10 14 L 25 14 L 14 26 Z M 27 14 L 16 26 L 30 26 Z M 10 14 L 30 14 M 10 26 L 30 26 M 20 26 L 12 34 L 6 34" fill="currentColor" fill-opacity="0.1" />`,
  },
  {
    id: "diac",
    type: "diac",
    name: "Diac (DB3 / BR100)",
    shortName: "DIAC",
    category: "semiconductores",
    categoryLabel: "Semiconductores",
    description: "Diodo de disparo bidireccional por tensión de ruptura simétrica (V_BO ≈ 32V).",
    defaultVal: "32",
    unit: "V",
    physicsEquation: "|V_{A1-A2}| \\ge V_{BO} \\implies \\text{Ruptura avalancha y snapback}",
    academicSummary: "Genera pulsos de encendido agudos para cebar compuertas de Triacs en circuitos dimmer.",
    spiceModelLevel: "Modelo Diac simétrico no lineal",
    isNonLinear: true,
    hasActiveBehavior: true,
    commercialSeries: ["DB3", "DB4", "BR100", "HT32"],
    packageFootprint: "DO-35",
    tags: ["diac", "db3", "diodo disparo", "ruptura", "dimmer", "disparo triac", "32v"],
    svgIconIeee: `<path d="M 20 4 L 20 14 M 20 26 L 20 36 M 10 14 L 25 14 L 14 26 Z M 27 14 L 16 26 L 30 26 Z M 10 14 L 30 14 M 10 26 L 30 26" fill="currentColor" fill-opacity="0.1" />`,
    svgIconIec: `<path d="M 20 4 L 20 14 M 20 26 L 20 36 M 10 14 L 25 14 L 14 26 Z M 27 14 L 16 26 L 30 26 Z M 10 14 L 30 14 M 10 26 L 30 26" fill="currentColor" fill-opacity="0.1" />`,
  },
  {
    id: "tl431",
    type: "tl431",
    name: "Regulador Shunt de Precisión TL431",
    shortName: "TL431",
    category: "semiconductores",
    categoryLabel: "Semiconductores",
    description: "Referencia de tensión programable de alta estabilidad (V_REF = 2.495V).",
    defaultVal: "2.495",
    unit: "V",
    physicsEquation: "V_K = V_{REF} \\cdot \\left(1 + \\frac{R_1}{R_2}\\right) + I_{REF} \\cdot R_1",
    academicSummary: "Zener programable con amplificador de error integrado para fuentes conmutadas (SMPS).",
    spiceModelLevel: "Macromodelo Shunt Regulator TL431",
    isNonLinear: true,
    hasActiveBehavior: true,
    commercialSeries: ["TL431", "LM431", "KA431", "TL432"],
    packageFootprint: "TO-92 / SOT-23 / SOIC-8",
    tags: ["tl431", "regulador shunt", "referencia", "zener ajustable", "smps", "2.495v", "lm431"],
    svgIconIeee: `<path d="M 20 4 L 20 14 M 20 26 L 20 36 M 10 26 L 30 26 L 20 14 Z M 10 14 L 30 14 M 10 10 L 10 14 M 30 14 L 30 18 M 4 20 L 16 20" fill="currentColor" fill-opacity="0.1" />`,
    svgIconIec: `<path d="M 20 4 L 20 14 M 20 26 L 20 36 M 10 26 L 30 26 L 20 14 Z M 10 14 L 30 14 M 10 10 L 10 14 M 30 14 L 30 18 M 4 20 L 16 20" fill="currentColor" fill-opacity="0.1" />`,
  },
  {
    id: "npn",
    type: "npn",
    name: "Transistor BJT NPN",
    shortName: "NPN",
    category: "semiconductores",
    categoryLabel: "Semiconductores",
    description: "Amplificador y conmutador controlado por corriente de base.",
    defaultVal: "100",
    unit: "β",
    hotkey: "Q",
    physicsEquation: "I_C = β · I_B = I_S · exp(V_BE / V_T) · (1 + V_CE / V_A)",
    academicSummary: "Modelo Gummel-Poon con saturación, corte y región activa lineal.",
    spiceModelLevel: "NPN (Gummel-Poon Level 1 con BF, IS, VAF, CJE, CJC)",
    isNonLinear: true,
    commercialSeries: ["2N2222", "BC547", "2N3904"],
    tags: ["transistor npn", "bjt", "bipolar", "amplificador", "2n2222", "bc547", "base", "colector", "emisor"],
    svgIconIeee: `<path d="M 14 10 L 14 30 M 14 20 L 4 20 M 14 14 L 28 6 L 28 4 M 14 26 L 28 34 L 28 36 M 28 34 L 21 34 M 28 34 L 26 27" />`,
    svgIconIec: `<circle cx="20" cy="20" r="14" /><path d="M 14 10 L 14 30 M 14 20 L 4 20 M 14 14 L 28 6 M 14 26 L 28 34 M 28 34 L 21 34 M 28 34 L 26 27" />`,
  },
  {
    id: "pnp",
    type: "pnp",
    name: "Transistor BJT PNP",
    shortName: "PNP",
    category: "semiconductores",
    categoryLabel: "Semiconductores",
    description: "Transistor bipolar polarizado en emisor positivo.",
    defaultVal: "100",
    unit: "β",
    physicsEquation: "I_C = β · I_B  (V_EB > 0.7 V)",
    academicSummary: "Complementario del NPN para etapas push-pull y espejos de corriente.",
    spiceModelLevel: "PNP (Gummel-Poon)",
    isNonLinear: true,
    commercialSeries: ["2N3906", "BC557"],
    tags: ["transistor pnp", "bjt", "bipolar", "2n3906", "bc557", "base", "colector", "emisor"],
    svgIconIeee: `<path d="M 14 10 L 14 30 M 14 20 L 4 20 M 14 14 L 28 6 L 28 4 M 14 26 L 28 34 L 28 36 M 14 26 L 21 23 M 14 26 L 17 31" />`,
    svgIconIec: `<circle cx="20" cy="20" r="14" /><path d="M 14 10 L 14 30 M 14 20 L 4 20 M 14 14 L 28 6 M 14 26 L 28 34 M 14 26 L 21 23 M 14 26 L 17 31" />`,
  },
  {
    id: "nmos",
    type: "nmos",
    name: "MOSFET Canal N",
    shortName: "NMOS",
    category: "semiconductores",
    categoryLabel: "Semiconductores",
    description: "Transistor de efecto de campo controlado por tensión V_GS.",
    defaultVal: "1.5",
    unit: "Vth",
    hotkey: "M",
    physicsEquation: "I_D = ½ k_n' (W/L) (V_GS - V_TH)² (1 + λ V_DS)",
    academicSummary: "Modela conducción por electrones en canal inducido. Resistencia de entrada casi infinita.",
    spiceModelLevel: "NMOS Shichman-Hodges (Level 1)",
    isNonLinear: true,
    commercialSeries: ["2N7000", "IRF540N"],
    tags: ["mosfet nmos", "transistor", "n-channel", "canal n", "conmutador", "gate", "drain", "source"],
    svgIconIeee: `<path d="M 23 10 L 23 30 M 15 12 L 15 28 M 15 20 L 4 20 M 23 12 L 29 12 L 29 4 M 23 28 L 29 28 L 29 36 M 23 28 L 26 25 M 23 28 L 26 31" />`,
    svgIconIec: `<circle cx="20" cy="20" r="14" /><path d="M 23 10 L 23 30 M 15 12 L 15 28 M 15 20 L 4 20 M 23 12 L 29 12 L 29 4 M 23 28 L 29 28 L 29 36" />`,
  },
  {
    id: "pmos",
    type: "pmos",
    name: "MOSFET Canal P",
    shortName: "PMOS",
    category: "semiconductores",
    categoryLabel: "Semiconductores",
    description: "MOSFET complementario para conmutación de riel alto y lógica CMOS.",
    defaultVal: "-1.5",
    unit: "Vth",
    physicsEquation: "I_D = ½ k_p' (W/L) (V_SG - |V_TH|)²",
    academicSummary: "Conducción por huecos. Clave en inversores y compuertas lógicas integradas.",
    spiceModelLevel: "PMOS Shichman-Hodges (Level 1)",
    isNonLinear: true,
    commercialSeries: ["BS250", "IRF9540"],
    tags: ["mosfet pmos", "transistor", "p-channel", "canal p", "gate", "drain", "source"],
    svgIconIeee: `<path d="M 23 10 L 23 30 M 17 12 L 17 28 M 13 20 L 4 20 M 23 12 L 29 12 L 29 4 M 23 28 L 29 28 L 29 36 M 23 12 L 26 15 M 23 12 L 26 9" /><circle cx="15" cy="20" r="2" />`,
    svgIconIec: `<circle cx="20" cy="20" r="14" /><path d="M 23 10 L 23 30 M 17 12 L 17 28 M 13 20 L 4 20 M 23 12 L 29 12 M 23 28 L 29 28" /><circle cx="15" cy="20" r="2" />`,
  },
  {
    id: "igbt",
    type: "igbt",
    name: "Transistor IGBT (Hefner NIST)",
    shortName: "IGBT",
    category: "semiconductores",
    categoryLabel: "Semiconductores",
    description: "Transistor bipolar de puerta aislada con dinámica de recombinación y corriente de cola (Tail Current).",
    defaultVal: "5.0",
    unit: "Vth",
    physicsEquation: "I_C = \\frac{I_{MOS}}{1 - \\alpha_{PNP}} + I_{tail}(t), \\quad \\frac{dQ_B}{dt} = \\alpha I_C - \\frac{Q_B}{\\tau_{HL}}",
    academicSummary: "Modelo físico avanzado NIST/Hefner que integra canal MOSFET de control y BJT PNP vertical de alta potencia con modulación de anchura de base y capacitancias parásitas dinámicas.",
    spiceModelLevel: "NIST Hefner Physical IGBT Model",
    isNonLinear: true,
    commercialSeries: ["IRG4BC30K", "FGA25N120", "IKW40N120H3"],
    packageFootprint: "TO-247 / TO-220",
    tags: ["igbt", "hefner", "nist", "potencia", "inversor", "vfd", "gate", "colector", "emisor", "tail current"],
    svgIconIeee: `<path d="M 14 10 L 14 30 M 14 20 L 4 20 M 18 10 L 18 30 M 18 14 L 28 6 L 28 4 M 18 26 L 28 34 L 28 36 M 28 34 L 21 34 M 28 34 L 26 27" />`,
    svgIconIec: `<circle cx="20" cy="20" r="14" /><path d="M 14 10 L 14 30 M 14 20 L 4 20 M 18 10 L 18 30 M 18 14 L 28 6 L 28 4 M 18 26 L 28 34 L 28 36 M 28 34 L 21 34 M 28 34 L 26 27" />`,
  },
  {
    id: "njf",
    type: "njf",
    name: "JFET Canal N",
    shortName: "JFET-N",
    category: "semiconductores",
    categoryLabel: "Semiconductores",
    description: "Transistor de unión con puerta polarizada en inversa (modo empobrecimiento).",
    defaultVal: "-2.0",
    unit: "Vp",
    physicsEquation: "I_D = I_DSS · (1 - V_GS / V_P)²",
    academicSummary: "Bajo ruido y altísima impedancia de entrada para preamplificadores de audio y RF.",
    spiceModelLevel: "JFET (Level 1)",
    isNonLinear: true,
    commercialSeries: ["2N5457", "BF245"],
    tags: ["jfet n", "transistor jfet", "canal n", "jfet", "jfet-n"],
    svgIconIeee: `<path d="M 23 10 L 23 30 M 14 20 L 23 20 M 23 12 L 29 12 L 29 4 M 23 28 L 29 28 L 29 36 M 18 16 L 22 20 L 18 24" fill="currentColor" />`,
    svgIconIec: `<circle cx="20" cy="20" r="14" /><path d="M 23 10 L 23 30 M 14 20 L 23 20 M 23 12 L 29 12 M 23 28 L 29 28" />`,
  },
  {
    id: "pjf",
    type: "pjf",
    name: "JFET Canal P",
    shortName: "JFET-P",
    category: "semiconductores",
    categoryLabel: "Semiconductores",
    description: "JFET de canal P en modo empobrecimiento.",
    defaultVal: "2.0",
    unit: "Vp",
    physicsEquation: "I_D = I_DSS · (1 - V_GS / V_P)²",
    academicSummary: "Complementario de canal P para fuentes de corriente de precisión.",
    spiceModelLevel: "JFET P (Level 1)",
    isNonLinear: true,
    commercialSeries: ["2N5460", "J176"],
    tags: ["jfet p", "transistor jfet", "canal p", "jfet", "jfet-p"],
    svgIconIeee: `<path d="M 23 10 L 23 30 M 14 20 L 23 20 M 23 12 L 29 12 L 29 4 M 23 28 L 29 28 L 29 36 M 18 20 L 14 16 L 14 24 Z" fill="currentColor" />`,
    svgIconIec: `<circle cx="20" cy="20" r="14" /><path d="M 23 10 L 23 30 M 14 20 L 23 20 M 23 12 L 29 12 M 23 28 L 29 28" />`,
  },
  {
    id: "opto",
    type: "opto",
    name: "Optoacoplador",
    shortName: "OPTO",
    category: "semiconductores",
    categoryLabel: "Semiconductores",
    description: "Aislamiento galvánico óptico emisor LED + fototransistor.",
    defaultVal: "1.0",
    unit: "CTR",
    physicsEquation: "I_C = CTR · I_F,  V_aisl > 2500 V",
    academicSummary: "Separa tierras de potencia de circuitos lógicos y microcontroladores sensibles.",
    spiceModelLevel: "Macromodelo acoplado LED-Fototransistor",
    isNonLinear: true,
    commercialSeries: ["PC817", "4N35", "4N25"],
    tags: ["optoacoplador", "aislador", "opto", "4n25", "4n35", "fototransistor", "aislamiento galvanico"],
    svgIconIeee: `<rect x="6" y="8" width="28" height="24" rx="2" fill="currentColor" fill-opacity="0.1" /><path d="M 12 14 L 12 26 M 28 14 L 28 26 M 16 20 L 24 20" stroke-dasharray="2 2" />`,
    svgIconIec: `<rect x="6" y="8" width="28" height="24" rx="2" fill="currentColor" fill-opacity="0.1" /><path d="M 12 14 L 12 26 M 28 14 L 28 26" />`,
  },
  {
    id: "bsim3nmos",
    type: "bsim3nmos",
    name: "BSIM3 NMOS Submicrónico",
    shortName: "BSIM3-N",
    category: "semiconductores",
    categoryLabel: "Semiconductores",
    description: "Modelo físico avanzado BSIM3v3.3 (Level 49) de 4 terminales (G, D, S, B).",
    defaultVal: "1.0",
    unit: "L=0.18µm",
    isExperimental: true,
    isNonLinear: true,
    physicsEquation: "I_ds = I_ds0 / (1 + R_ds I_ds0 / V_dseff) · [1 + (V_ds - V_dseff)/V_A]",
    academicSummary: "Incluye DIBL, modulación de longitud de canal, efectos de sustrato y portadores calientes.",
    spiceModelLevel: "BSIM3v3.3 (Level 49)",
    tags: ["bsim", "bsim3", "submicronico", "vlsi", "cmos", "ic", "nmos", "experimental"],
    svgIconIeee: `<path d="M 23 10 L 23 30 M 15 12 L 15 28 M 15 20 L 4 20 M 23 12 L 29 12 L 29 4 M 23 28 L 29 28 L 29 36 M 23 20 L 36 20" />`,
    svgIconIec: `<path d="M 23 10 L 23 30 M 15 12 L 15 28 M 15 20 L 4 20 M 23 12 L 29 12 M 23 28 L 29 28 M 23 20 L 36 20" />`,
  },
  {
    id: "bsim3pmos",
    type: "bsim3pmos",
    name: "BSIM3 PMOS Submicrónico",
    shortName: "BSIM3-P",
    category: "semiconductores",
    categoryLabel: "Semiconductores",
    description: "Modelo físico submicrónico BSIM3v3.3 PMOS (Level 49) de 4 terminales.",
    defaultVal: "-1.0",
    unit: "L=0.18µm",
    isExperimental: true,
    isNonLinear: true,
    physicsEquation: "I_ds(V_gs, V_ds, V_bs)  BSIM3v3.3",
    academicSummary: "Modelado submicrónico de tecnología CMOS profunda para diseño VLSI.",
    spiceModelLevel: "BSIM3v3.3 (Level 49)",
    tags: ["bsim", "bsim3", "submicronico", "vlsi", "cmos", "ic", "pmos", "experimental"],
    svgIconIeee: `<path d="M 23 10 L 23 30 M 17 12 L 17 28 M 13 20 L 4 20 M 23 12 L 29 12 L 29 4 M 23 28 L 29 28 L 29 36 M 23 20 L 36 20" /><circle cx="15" cy="20" r="2" />`,
    svgIconIec: `<path d="M 23 10 L 23 30 M 17 12 L 17 28 M 13 20 L 4 20 M 23 12 L 29 12 M 23 28 L 29 28 M 23 20 L 36 20" /><circle cx="15" cy="20" r="2" />`,
  },

  // ─── ANALÓGICOS & FUENTES ─────────────────────────────────────────────
  {
    id: "opamp_ideal",
    type: "opamp_ideal",
    name: "Op-Amp Ideal (3 pines)",
    shortName: "OP-IDEAL",
    category: "analogicos",
    categoryLabel: "Analógicos",
    description: "Amplificador operacional con ganancia infinita Av → ∞ y Rin → ∞.",
    defaultVal: "0",
    unit: "Av=∞",
    hotkey: "A",
    physicsEquation: "V_out = A_OL (V_+ - V_-),  V_+ = V_-  (Cortocircuito Virtual)",
    academicSummary: "Idealización pedagógica para análisis rápido de filtros activos, integradores y sumadores.",
    spiceModelLevel: "Fuente de tensión controlada VCVS de muy alta ganancia (1e6)",
    tags: ["amplificador operacional ideal", "opamp", "ao", "comparador", "inversor", "ganancia infinita"],
    svgIconIeee: `<path d="M 12 10 L 12 30 L 28 20 Z M 4 15 L 12 15 M 4 25 L 12 25 M 28 20 L 36 20 M 14 15 L 18 15 M 16 13 L 16 17 M 14 25 L 18 25" />`,
    svgIconIec: `<rect x="10" y="8" width="20" height="24" rx="2" fill="currentColor" fill-opacity="0.1" /><text x="20" y="23" text-anchor="middle" font-size="10" font-weight="bold" fill="currentColor">&amp;</text>`,
  },
  {
    id: "opamp",
    type: "opamp",
    name: "Op-Amp Real (5 pines)",
    shortName: "OPAMP",
    category: "analogicos",
    categoryLabel: "Analógicos",
    description: "Amplificador operacional con rieles de alimentación (VCC+, VEE-), saturación y slew rate.",
    defaultVal: "0",
    unit: "5-Pin",
    physicsEquation: "V_EE ≤ V_out ≤ V_CC,  |dV_out/dt| ≤ SR",
    academicSummary: "Modela límites de excursión de tensión y respuesta en frecuencia polos/ceros realistas.",
    spiceModelLevel: "Macromodelo Boyle / LM741 / TL081",
    commercialSeries: ["TL081", "LM741", "NE5532", "OPA2134"],
    packageFootprint: "DIP-8 / SOIC-8",
    tags: ["amplificador operacional", "opamp", "ao", "tl081", "lm741", "ne5532", "inversor", "no inversor"],
    svgIconIeee: `<path d="M 12 10 L 12 30 L 28 20 Z M 4 15 L 12 15 M 4 25 L 12 25 M 28 20 L 36 20 M 20 14 L 20 4 M 20 26 L 20 36" />`,
    svgIconIec: `<rect x="10" y="8" width="20" height="24" rx="2" fill="currentColor" fill-opacity="0.1" /><text x="20" y="23" text-anchor="middle" font-size="10" font-weight="bold" fill="currentColor">▷</text>`,
  },
  {
    id: "comparator_ideal",
    type: "comparator_ideal",
    name: "Comparador Ideal (3 pines)",
    shortName: "COMP-IDEAL",
    category: "analogicos",
    categoryLabel: "Analógicos",
    description: "Comparador de tensión de alta velocidad con salida de conmutación instantánea.",
    defaultVal: "0",
    unit: "3-Pin",
    physicsEquation: "V_out = +V_sat si V_+ > V_-,  V_out = -V_sat si V_+ < V_-",
    academicSummary: "Dispositivo de decisión no lineal para detectores de cruce por cero, conformadores de pulso y comparadores de nivel.",
    spiceModelLevel: "Etapa diferencial saturada de conmutación sin retardo",
    tags: ["comparador ideal", "comparador", "comparator", "schmitt", "detector de cruce", "cero", "lm393", "lm311"],
    svgIconIeee: `<path d="M 12 10 L 12 30 L 28 20 Z M 4 15 L 12 15 M 4 25 L 12 25 M 28 20 L 36 20 M 14 15 L 18 15 M 16 13 L 16 17 M 14 25 L 18 25" /><text x="18" y="22" font-size="7" font-weight="bold" fill="currentColor">C</text>`,
    svgIconIec: `<rect x="10" y="8" width="20" height="24" rx="2" fill="currentColor" fill-opacity="0.1" /><text x="20" y="23" text-anchor="middle" font-size="9" font-weight="bold" fill="currentColor">&gt;</text>`,
  },
  {
    id: "vsource",
    type: "vsource",
    name: "Fuente de Tensión",
    shortName: "VSRC",
    category: "analogicos",
    categoryLabel: "Analógicos",
    description: "Generador de tensión CC, CA senoidal, pulso, rampa o exponencial.",
    defaultVal: "5",
    unit: "V",
    hotkey: "V",
    physicsEquation: "V(t) = V_DC + V_AC · sin(2π f t + φ)",
    academicSummary: "Establece la diferencia de potencial independiente de la corriente demandada.",
    spiceModelLevel: "V (Fuente independiente de tensión MNA)",
    tags: ["fuente de tension", "voltaje", "bateria", "vsource", "vcc", "power", "alimentacion", "dc", "pila", "generador"],
    svgIconIeee: `<circle cx="20" cy="20" r="14" fill="currentColor" fill-opacity="0.1" /><path d="M 10 20 L 18 20 M 14 16 L 14 24 M 22 20 L 30 20" />`,
    svgIconIec: `<circle cx="20" cy="20" r="14" fill="currentColor" fill-opacity="0.1" /><path d="M 4 20 L 36 20" />`,
  },
  {
    id: "isource",
    type: "isource",
    name: "Fuente de Corriente",
    shortName: "ISRC",
    category: "analogicos",
    categoryLabel: "Analógicos",
    description: "Generador de corriente constante o periódica inyectada al circuito.",
    defaultVal: "0.01",
    unit: "A",
    hotkey: "I",
    physicsEquation: "I(t) = I_DC + I_AC · sin(ω t)",
    academicSummary: "Impone una corriente fija independientemente de la impedancia de carga conectada.",
    spiceModelLevel: "I (Fuente independiente de corriente MNA)",
    tags: ["fuente de corriente", "corriente", "amperios", "isource", "intensidad", "generador corriente"],
    svgIconIeee: `<circle cx="20" cy="20" r="14" fill="currentColor" fill-opacity="0.1" /><path d="M 14 14 L 20 20 L 14 26 M 20 20 L 26 20" />`,
    svgIconIec: `<circle cx="16" cy="20" r="10" /><circle cx="24" cy="20" r="10" />`,
  },
  {
    id: "vcvs",
    type: "vcvs",
    name: "Fuente de Tensión Controlada por Tensión (VCVS)",
    shortName: "VCVS",
    category: "analogicos",
    categoryLabel: "Analógicos",
    description: "Generador dependiente de tensión lineal (V_out = Av · V_in).",
    defaultVal: "1.0",
    unit: "V/V",
    physicsEquation: "V_{out} = A_v \\cdot (V_{in}^+ - V_{in}^-)",
    academicSummary: "Representa amplificadores de tensión y modelos de cuadripolos en pequeña señal.",
    spiceModelLevel: "E (VCVS - SPICE Dependent Source)",
    tags: ["vcvs", "fuente controlada", "fuente dependiente", "e source", "ganancia", "thevenin", "pequeña señal"],
    svgIconIeee: `<polygon points="20,8 32,20 20,32 8,20" fill="currentColor" fill-opacity="0.1" stroke="currentColor" /><path d="M 17 17 L 23 17 M 20 14 L 20 20 M 17 25 L 23 25" />`,
    svgIconIec: `<polygon points="20,8 32,20 20,32 8,20" fill="currentColor" fill-opacity="0.1" stroke="currentColor" /><path d="M 17 17 L 23 17 M 20 14 L 20 20 M 17 25 L 23 25" />`,
  },
  {
    id: "vccs",
    type: "vccs",
    name: "Fuente de Corriente Controlada por Tensión (VCCS)",
    shortName: "VCCS",
    category: "analogicos",
    categoryLabel: "Analógicos",
    description: "Generador dependiente de corriente por transconductancia (I_out = gm · V_in).",
    defaultVal: "0.001",
    unit: "S",
    physicsEquation: "I_{out} = g_m \\cdot (V_{in}^+ - V_{in}^-)",
    academicSummary: "Modela la transconductancia fundamental de transistores BJT y MOSFET.",
    spiceModelLevel: "G (VCCS - SPICE Dependent Source)",
    tags: ["vccs", "transconductancia", "gm", "g source", "fuente dependiente corriente", "ota"],
    svgIconIeee: `<polygon points="20,8 32,20 20,32 8,20" fill="currentColor" fill-opacity="0.1" stroke="currentColor" /><path d="M 20 26 L 20 14 M 16 18 L 20 14 L 24 18" />`,
    svgIconIec: `<polygon points="20,8 32,20 20,32 8,20" fill="currentColor" fill-opacity="0.1" stroke="currentColor" /><path d="M 20 26 L 20 14 M 16 18 L 20 14 L 24 18" />`,
  },
  {
    id: "ccvs",
    type: "ccvs",
    name: "Fuente de Tensión Controlada por Corriente (CCVS)",
    shortName: "CCVS",
    category: "analogicos",
    categoryLabel: "Analógicos",
    description: "Generador dependiente de tensión por transresistencia (V_out = Rm · I_in).",
    defaultVal: "1000",
    unit: "Ω",
    physicsEquation: "V_{out} = R_m \\cdot I_{in}",
    academicSummary: "Representa amplificadores de transimpedancia y sensores de corriente.",
    spiceModelLevel: "H (CCVS - SPICE Dependent Source)",
    tags: ["ccvs", "transresistencia", "transimpedancia", "h source", "fuente controlada por corriente"],
    svgIconIeee: `<polygon points="20,8 32,20 20,32 8,20" fill="currentColor" fill-opacity="0.1" stroke="currentColor" /><path d="M 6 12 L 6 28 M 17 17 L 23 17 M 20 14 L 20 20 M 17 25 L 23 25" />`,
    svgIconIec: `<polygon points="20,8 32,20 20,32 8,20" fill="currentColor" fill-opacity="0.1" stroke="currentColor" /><path d="M 6 12 L 6 28 M 17 17 L 23 17 M 20 14 L 20 20 M 17 25 L 23 25" />`,
  },
  {
    id: "cccs",
    type: "cccs",
    name: "Fuente de Corriente Controlada por Corriente (CCCS)",
    shortName: "CCCS",
    category: "analogicos",
    categoryLabel: "Analógicos",
    description: "Generador dependiente de corriente con ganancia de corriente (I_out = Ai · I_in).",
    defaultVal: "1.0",
    unit: "A/A",
    physicsEquation: "I_{out} = A_i \\cdot I_{in}",
    academicSummary: "Modela la ganancia beta de transistores BJT y espejos de corriente.",
    spiceModelLevel: "F (CCCS - SPICE Dependent Source)",
    tags: ["cccs", "espejo de corriente", "ganancia corriente", "beta", "f source", "fuente dependiente"],
    svgIconIeee: `<polygon points="20,8 32,20 20,32 8,20" fill="currentColor" fill-opacity="0.1" stroke="currentColor" /><path d="M 6 12 L 6 28 M 20 26 L 20 14 M 16 18 L 20 14 L 24 18" />`,
    svgIconIec: `<polygon points="20,8 32,20 20,32 8,20" fill="currentColor" fill-opacity="0.1" stroke="currentColor" /><path d="M 6 12 L 6 28 M 20 26 L 20 14 M 16 18 L 20 14 L 24 18" />`,
  },

  // ─── ACTUADORES E INTERRUPTORES ───────────────────────────────────────
  {
    id: "lamp",
    type: "lamp",
    name: "Lámpara Incandescente",
    shortName: "LAMP",
    category: "actuadores",
    categoryLabel: "Actuadores",
    description: "Bombilla resistiva con inercia térmica, brillo dinámico y protección de filamento.",
    defaultVal: "12V 5W",
    unit: "12V/5W",
    physicsEquation: "R(T) = R_cold · [1 + α(T - T₀)], P = V² / R",
    academicSummary: "Modela la no-linealidad térmica del filamento de tungsteno con animación física de resplandor.",
    spiceModelLevel: "Macromodelo electro-térmico no lineal",
    hasActiveBehavior: true,
    commercialSeries: ["6V 2W", "12V 5W", "24V 10W", "120V 40W", "230V 60W"],
    tags: ["lampara", "bombilla", "foco", "filamento", "luz", "actuador", "termico"],
    svgIconIeee: `<circle cx="20" cy="20" r="12" fill="currentColor" fill-opacity="0.1" /><path d="M 11.5 11.5 L 28.5 28.5 M 28.5 11.5 L 11.5 28.5" />`,
    svgIconIec: `<circle cx="20" cy="20" r="12" /><path d="M 11.5 11.5 L 28.5 28.5 M 28.5 11.5 L 11.5 28.5" />`,
  },
  {
    id: "relay",
    type: "relay",
    name: "Relé Electromecánico SPDT (5 Pines)",
    shortName: "RELAY",
    category: "actuadores",
    categoryLabel: "Actuadores",
    description: "Relé SPDT de 5 pines con bobina magnética, contacto COM y salidas NO / NC.",
    defaultVal: "12V",
    unit: "SPDT 5P",
    physicsEquation: "I_coil ≥ I_pull ⇒ Conmuta COM a NO,  I_coil < I_hold ⇒ Retorna COM a NC",
    academicSummary: "Aislamiento galvánico con conmutación electromagnética animada entre contactos NC y NO.",
    spiceModelLevel: "Interruptor dependiente de corriente con histéresis e inductancia",
    hasActiveBehavior: true,
    commercialSeries: ["SRD-05VDC-SL-C", "SRD-12VDC-SL-C", "G5LE-1 24V"],
    tags: ["rele", "relay", "bobina", "contacto", "relevador", "spdt", "5 pines", "nc", "no", "com"],
    svgIconIeee: `<rect x="8" y="10" width="10" height="20" rx="1" fill="currentColor" fill-opacity="0.1" /><path d="M 8 10 L 18 30 M 26 12 L 26 18 M 26 28 L 26 22 M 26 18 L 32 20" />`,
    svgIconIec: `<rect x="8" y="10" width="10" height="20" rx="1" fill="currentColor" fill-opacity="0.1" /><path d="M 8 10 L 18 30 M 26 10 L 26 30" />`,
  },
  {
    id: "buzzer",
    type: "buzzer",
    name: "Zumbador Piezoeléctrico (Buzzer)",
    shortName: "BUZZER",
    category: "actuadores",
    categoryLabel: "Actuadores",
    description: "Aviso sonoro electroacústico con síntesis de audio Web Audio API acoplada.",
    defaultVal: "5V 2.4kHz",
    unit: "5V/2.4kHz",
    physicsEquation: "f₀ ≈ 2400 Hz,  SPL ∝ V_in",
    academicSummary: "Transductor electroacústico resonante con síntesis de sonido y ondas acústicas animadas.",
    spiceModelLevel: "Carga dinámica con transductor acústico",
    hasActiveBehavior: true,
    tags: ["zumbador", "buzzer", "altavoz", "audio", "tono", "bip", "sonido", "frecuencia"],
    svgIconIeee: `<path d="M 10 12 H 18 L 28 6 V 34 L 18 28 H 10 Z" fill="currentColor" fill-opacity="0.1" /><path d="M 32 15 C 34 17, 34 23, 32 25" />`,
    svgIconIec: `<rect x="8" y="12" width="12" height="16" rx="2" /><path d="M 20 10 L 30 6 V 34 L 20 30 Z" fill="currentColor" fill-opacity="0.1" />`,
  },
  {
    id: "switch",
    type: "switch",
    name: "Interruptor SPST",
    shortName: "SW",
    category: "actuadores",
    categoryLabel: "Actuadores",
    description: "Interruptor unipolar de 1 tiro (SPST) con palanca basculante interactiva.",
    defaultVal: "SPST",
    unit: "SPST",
    hotkey: "S",
    physicsEquation: "R_SW = 10 mΩ (Cerrado) / 1 GΩ (Abierto)",
    academicSummary: "Permite probar cortes de alimentación y estímulos paso a paso interactivamente.",
    spiceModelLevel: "S (Interruptor controlado MNA)",
    hasActiveBehavior: true,
    tags: ["interruptor", "switch", "llave", "spst", "abierto", "cerrado"],
    svgIconIeee: `<path d="M 4 20 L 14 20 M 26 20 L 36 20 M 14 20 L 26 12" /><circle cx="14" cy="20" r="2" /><circle cx="26" cy="20" r="2" />`,
    svgIconIec: `<path d="M 4 20 L 14 20 M 26 20 L 36 20 M 14 20 L 26 12" /><circle cx="14" cy="20" r="2" /><circle cx="26" cy="20" r="2" />`,
  },
  {
    id: "switch_spdt",
    type: "switch_spdt",
    name: "Conmutador SPDT (1P2T)",
    shortName: "SPDT",
    category: "actuadores",
    categoryLabel: "Actuadores",
    description: "Conmutador unipolar de 2 posiciones (COM, T1, T2) para selección de vías.",
    defaultVal: "SPDT",
    unit: "SPDT",
    physicsEquation: "Pos 0: COM-T1  |  Pos 1: COM-T2",
    academicSummary: "Conmutación de dos caminos eléctricos ideal para selección de fuentes y lógica de relé.",
    spiceModelLevel: "S (Interruptor SPDT bidireccional)",
    hasActiveBehavior: true,
    tags: ["conmutador", "spdt", "switch", "2 vias", "selector", "com", "t1", "t2"],
    svgIconIeee: `<path d="M 4 20 L 14 20 M 26 12 L 36 12 M 26 28 L 36 28 M 14 20 L 26 12" /><circle cx="14" cy="20" r="2" /><circle cx="26" cy="12" r="2" /><circle cx="26" cy="28" r="2" />`,
    svgIconIec: `<path d="M 4 20 L 14 20 M 26 12 L 36 12 M 26 28 L 36 28 M 14 20 L 26 12" /><circle cx="14" cy="20" r="2" /><circle cx="26" cy="12" r="2" /><circle cx="26" cy="28" r="2" />`,
  },
  {
    id: "switch_dpdt",
    type: "switch_dpdt",
    name: "Conmutador DPDT (2P2T)",
    shortName: "DPDT",
    category: "actuadores",
    categoryLabel: "Actuadores",
    description: "Conmutador bipolar de 2 tiros (6 pines) para inversión de polaridad o giro de motores.",
    defaultVal: "DPDT",
    unit: "DPDT",
    physicsEquation: "Inversión de polaridad sincronizada en 2 polos",
    academicSummary: "Doble polo sincronizado mecánicamente. El estándar industrial para puentes de inversión.",
    spiceModelLevel: "S (Doble interruptor acoplado)",
    hasActiveBehavior: true,
    tags: ["conmutador", "dpdt", "inversion", "motor", "polaridad", "puente h", "6 pines"],
    svgIconIeee: `<path d="M 4 12 L 14 12 M 26 8 L 36 8 M 26 16 L 36 16 M 14 12 L 26 8 M 4 28 L 14 28 M 26 24 L 36 24 M 26 32 L 36 32 M 14 28 L 26 24" /><line x1="20" y1="10" x2="20" y2="26" stroke-dasharray="2 2" />`,
    svgIconIec: `<path d="M 4 12 L 14 12 M 26 8 L 36 8 M 26 16 L 36 16 M 14 12 L 26 8 M 4 28 L 14 28 M 26 24 L 36 24 M 26 32 L 36 32 M 14 28 L 26 24" /><line x1="20" y1="10" x2="20" y2="26" stroke-dasharray="2 2" />`,
  },
  {
    id: "pushbutton",
    type: "pushbutton",
    name: "Pulsador Momentáneo (Pushbutton)",
    shortName: "PB",
    category: "actuadores",
    categoryLabel: "Actuadores",
    description: "Pulsador táctil normalmente abierto (NO) o normalmente cerrado (NC).",
    defaultVal: "NO",
    unit: "PB",
    physicsEquation: "Conduce únicamente durante la pulsación activa",
    academicSummary: "Elemento de entrada táctil para reinicio de microcontroladores y pulsos manuales de reloj.",
    spiceModelLevel: "S (Interruptor transitorio momentáneo)",
    hasActiveBehavior: true,
    tags: ["pulsador", "pushbutton", "boton", "tactil", "no", "nc", "reset", "pulso"],
    svgIconIeee: `<path d="M 4 20 L 14 20 M 26 20 L 36 20 M 10 14 H 30 M 20 14 V 6 M 14 6 H 26" /><circle cx="14" cy="20" r="2" /><circle cx="26" cy="20" r="2" />`,
    svgIconIec: `<path d="M 4 20 L 14 20 M 26 20 L 36 20 M 10 14 H 30 M 20 14 V 6 M 14 6 H 26" /><circle cx="14" cy="20" r="2" /><circle cx="26" cy="20" r="2" />`,
  },
  {
    id: "dc_motor",
    type: "dc_motor",
    name: "Motor DC (Corriente Continua)",
    shortName: "DC-MOT",
    category: "actuadores",
    categoryLabel: "Actuadores",
    description: "Motor electromecánico con rotación en RPM, fuerza contraelectromotriz y par.",
    defaultVal: "12V 3000RPM",
    unit: "12V/RPM",
    physicsEquation: "E = K_e · ω,  T = K_t · I_a,  V = E + I_a · R_a",
    academicSummary: "Modela la conversión electromecánica con animación de giro proporcional a la tensión.",
    spiceModelLevel: "Macromodelo electromecánico de 2do orden",
    hasActiveBehavior: true,
    commercialSeries: ["RS-550 12V", "N20 Mini 6V", "Mabuchi 130 3V"],
    tags: ["motor", "dc", "rotor", "giro", "rpm", "electromecanico", "torque", "back-emf"],
    svgIconIeee: `<circle cx="20" cy="20" r="12" fill="currentColor" fill-opacity="0.1" /><path d="M 4 20 H 8 M 32 20 H 36" /><text x="20" y="24" text-anchor="middle" font-size="11" font-weight="bold" fill="currentColor">M</text>`,
    svgIconIec: `<circle cx="20" cy="20" r="12" /><path d="M 4 20 H 8 M 32 20 H 36" /><text x="20" y="24" text-anchor="middle" font-size="11" font-weight="bold" fill="currentColor">M</text>`,
  },
  {
    id: "seven_segment",
    type: "seven_segment",
    name: "Display de 7 Segmentos (10 Pines)",
    shortName: "7-SEG",
    category: "actuadores",
    categoryLabel: "Actuadores",
    description: "Display numérico de 7 segmentos LED más punto decimal con pinout DIP de 10 pines.",
    defaultVal: "Catodo Común",
    unit: "DIP-10",
    physicsEquation: "I_seg = (V_anodo - V_catodo - 1.8V) / R_lim",
    academicSummary: "Visualizador optoelectrónico clásico para decodificadores BCD (74HC47/48) y MCUs.",
    spiceModelLevel: "Matriz de 8 diodos LED con terminales comunes",
    hasActiveBehavior: true,
    commercialSeries: ["5161AS (Cátodo)", "5161BS (Ánodo)"],
    tags: ["display", "7 segmentos", "seven segment", "led", "contador", "bcd", "numero", "digito"],
    svgIconIeee: `<rect x="8" y="4" width="24" height="32" rx="2" fill="currentColor" fill-opacity="0.1" /><path d="M 12 8 H 28 M 28 8 V 20 M 28 20 V 32 M 12 32 H 28 M 12 20 V 32 M 12 8 V 20 M 12 20 H 28" stroke-width="2" />`,
    svgIconIec: `<rect x="8" y="4" width="24" height="32" rx="2" fill="currentColor" fill-opacity="0.1" /><path d="M 12 8 H 28 M 28 8 V 20 M 28 20 V 32 M 12 32 H 28 M 12 20 V 32 M 12 8 V 20 M 12 20 H 28" stroke-width="2" />`,
  },
  {
    id: "servo_motor",
    type: "servo_motor",
    name: "Servomotor RC (SG90)",
    shortName: "SERVO",
    category: "actuadores",
    categoryLabel: "Actuadores",
    description: "Servomotor con control angular de 0° a 180° modulado por señal PWM.",
    defaultVal: "SG90 0-180°",
    unit: "0-180°",
    physicsEquation: "θ = clamp(0°, 180°, (V_pwm / 5V) · 180°)",
    academicSummary: "Actuador servo con lazo cerrado de posición interna y brazo móvil animado.",
    spiceModelLevel: "Macromodelo servo posición con impedancia de control",
    hasActiveBehavior: true,
    commercialSeries: ["TowerPro SG90", "MG90S Metal Gear", "MG996R"],
    tags: ["servo", "servomotor", "sg90", "pwm", "angulo", "posicion", "brazo", "robotica"],
    svgIconIeee: `<rect x="8" y="10" width="24" height="20" rx="2" fill="#0284C7" fill-opacity="0.2" stroke="#0284C7" /><circle cx="20" cy="20" r="5" fill="#E2E8F0" /><line x1="20" y1="20" x2="30" y2="12" stroke="#F8FAFC" stroke-width="2" />`,
    svgIconIec: `<rect x="8" y="10" width="24" height="20" rx="2" fill="#0284C7" fill-opacity="0.2" stroke="#0284C7" /><circle cx="20" cy="20" r="5" fill="#E2E8F0" /><line x1="20" y1="20" x2="30" y2="12" stroke="#F8FAFC" stroke-width="2" />`,
  },
  {
    id: "stepper_motor",
    type: "stepper_motor",
    name: "Motor Paso a Paso Bipolar (4 Fases)",
    shortName: "STEPPER",
    category: "actuadores",
    categoryLabel: "Actuadores",
    description: "Motor paso a paso bifásico (NEMA 17) para control de posicionamiento angular preciso.",
    defaultVal: "NEMA 17",
    unit: "1.8°/Paso",
    physicsEquation: "θ_k = θ_{k-1} + Δθ · sign(I_A · I_B)",
    academicSummary: "Motor síncrono sin escobillas con rotor de imán permanente y control por secuencias de fase.",
    spiceModelLevel: "Doble bobinado acoplado con resistencia e inductancia",
    hasActiveBehavior: true,
    commercialSeries: ["NEMA 17 (42x42mm)", "28BYJ-48 5V", "NEMA 23"],
    tags: ["stepper", "paso a paso", "nema", "posicionamiento", "motor", "fases", "cnc", "3d"],
    svgIconIeee: `<circle cx="20" cy="20" r="13" fill="currentColor" fill-opacity="0.1" stroke="currentColor" /><circle cx="20" cy="20" r="6" stroke="#38BDF8" /><line x1="20" y1="20" x2="20" y2="10" stroke="#EF4444" stroke-width="2" />`,
    svgIconIec: `<circle cx="20" cy="20" r="13" fill="currentColor" fill-opacity="0.1" stroke="currentColor" /><circle cx="20" cy="20" r="6" stroke="#38BDF8" /><line x1="20" y1="20" x2="20" y2="10" stroke="#EF4444" stroke-width="2" />`,
  },
  {
    id: "speaker",
    type: "speaker",
    name: "Altavoz Dinámico (8Ω)",
    shortName: "SPK",
    category: "actuadores",
    categoryLabel: "Actuadores",
    description: "Transductor electroacústico de bobina móvil con 8Ω de impedancia nominal.",
    defaultVal: "8Ω 0.5W",
    unit: "8Ω",
    physicsEquation: "P = V_rms² / 8Ω,  F_lorentz = B · I · L",
    academicSummary: "Conversión de señal eléctrica de audio a ondas de presión acústica con animación de diafragma.",
    spiceModelLevel: "Carga inductivo-resistiva de audio (8Ω + 0.5mH)",
    hasActiveBehavior: true,
    commercialSeries: ["8Ω 0.5W Mini", "8Ω 2W", "4Ω 3W"],
    tags: ["altavoz", "speaker", "audio", "parlante", "sonido", "8 ohm", "acustico"],
    svgIconIeee: `<path d="M 8 14 H 14 L 24 8 V 32 L 14 26 H 8 Z" fill="currentColor" fill-opacity="0.15" stroke="currentColor" /><path d="M 27 15 C 29 18, 29 22, 27 25" stroke="#38BDF8" stroke-width="1.5" />`,
    svgIconIec: `<path d="M 8 14 H 14 L 24 8 V 32 L 14 26 H 8 Z" fill="currentColor" fill-opacity="0.15" stroke="currentColor" /><path d="M 27 15 C 29 18, 29 22, 27 25" stroke="#38BDF8" stroke-width="1.5" />`,
  },
  {
    id: "solenoid",
    type: "solenoid",
    name: "Solenoide / Actuador Lineal",
    shortName: "SOL",
    category: "actuadores",
    categoryLabel: "Actuadores",
    description: "Actuador electromecánico lineal con émbolo retráctil accionado por corriente.",
    defaultVal: "12V 10N",
    unit: "12V",
    physicsEquation: "F = ½ · I² · (dL/dx),  I_act ≥ 0.25A",
    academicSummary: "Transductor lineal electromagnético con desplazamiento animado de núcleo férrico y muelle.",
    spiceModelLevel: "Bobina con resistencia e inductancia parásitas (24Ω + 50mH)",
    hasActiveBehavior: true,
    commercialSeries: ["JF-0530B 12V", "ZYE1-0530 5V", "Push-Pull 24V"],
    tags: ["solenoide", "actuador", "lineal", "embolo", "cerradura", "bobina", "fuerza"],
    svgIconIeee: `<rect x="10" y="12" width="20" height="16" rx="1" fill="#F59E0B" fill-opacity="0.15" stroke="#F59E0B" /><rect x="4" y="16" width="10" height="8" fill="#94A3B8" stroke="#64748B" />`,
    svgIconIec: `<rect x="10" y="12" width="20" height="16" rx="1" fill="#F59E0B" fill-opacity="0.15" stroke="#F59E0B" /><rect x="4" y="16" width="10" height="8" fill="#94A3B8" stroke="#64748B" />`,
  },
  {
    id: "ssr",
    type: "ssr",
    name: "Relé de Estado Sólido (SSR)",
    shortName: "SSR",
    category: "actuadores",
    categoryLabel: "Actuadores",
    description: "Relé optoacoplado sin partes móviles para conmutación silenciosa de cargas de potencia.",
    defaultVal: "3-32VDC / 240VAC",
    unit: "SSR",
    physicsEquation: "V_ctrl ≥ 3V ⇒ R_load = 50mΩ,  V_ctrl < 3V ⇒ R_load = 100MΩ",
    academicSummary: "Aislamiento galvánico óptico de alta velocidad sin rebotes mecánicos ni arco eléctrico.",
    spiceModelLevel: "Interruptor dependiente de tensión optoaislado",
    hasActiveBehavior: true,
    commercialSeries: ["SSR-25DA", "SSR-40DA", "Fotek 10A"],
    tags: ["ssr", "rele estado solido", "solid state", "optotriac", "conmutacion", "potencia"],
    svgIconIeee: `<rect x="8" y="6" width="24" height="28" rx="2" fill="currentColor" fill-opacity="0.12" stroke="currentColor" /><circle cx="20" cy="12" r="3" fill="#10B981" /><text x="20" y="26" text-anchor="middle" font-size="7" font-weight="bold" fill="#38BDF8">SSR</text>`,
    svgIconIec: `<rect x="8" y="6" width="24" height="28" rx="2" fill="currentColor" fill-opacity="0.12" stroke="currentColor" /><circle cx="20" cy="12" r="3" fill="#10B981" /><text x="20" y="26" text-anchor="middle" font-size="7" font-weight="bold" fill="#38BDF8">SSR</text>`,
  },

  // ─── LÓGICA DIGITAL ───────────────────────────────────────────────────
  {
    id: "and_gate",
    type: "and_gate",
    name: "Compuerta AND",
    shortName: "AND",
    category: "logica-digital",
    categoryLabel: "Lógica Digital",
    description: "Función de conjunción lógica (Y = A · B).",
    defaultVal: "1",
    unit: "TTL",
    physicsEquation: "Y = A ∧ B,  V_OH = 5.0 V,  V_OL = 0.0 V",
    academicSummary: "Modelo con niveles lógicos analógicos continuos e histéresis Schmitt de entrada.",
    spiceModelLevel: "Subcircuito lógico analógico con retardo de propagación",
    commercialSeries: ["74HC08", "74LS08"],
    packageFootprint: "DIP-14",
    tags: ["compuerta and", "y logica", "7408", "digital", "and", "logica"],
    svgIconIeee: `<path d="M 4 14 L 14 14 M 4 26 L 14 26 M 30 20 L 36 20 M 14 8 L 22 8 C 28 8, 30 14, 30 20 C 30 26, 28 32, 22 32 L 14 32 Z" fill="currentColor" fill-opacity="0.1" />`,
    svgIconIec: `<rect x="10" y="8" width="20" height="24" rx="2" fill="currentColor" fill-opacity="0.1" /><text x="20" y="24" text-anchor="middle" font-size="12" font-weight="bold" fill="currentColor">&amp;</text><path d="M 4 14 L 10 14 M 4 26 L 10 26 M 30 20 L 36 20" />`,
  },
  {
    id: "or_gate",
    type: "or_gate",
    name: "Compuerta OR",
    shortName: "OR",
    category: "logica-digital",
    categoryLabel: "Lógica Digital",
    description: "Función de disyunción lógica (Y = A + B).",
    defaultVal: "1",
    unit: "TTL",
    physicsEquation: "Y = A ∨ B",
    academicSummary: "Salida en nivel alto si al menos una de las entradas supera el umbral V_IH.",
    spiceModelLevel: "Subcircuito lógico analógico",
    commercialSeries: ["74HC32", "74LS32"],
    packageFootprint: "DIP-14",
    tags: ["compuerta or", "o logica", "7432", "digital", "or", "logica"],
    svgIconIeee: `<path d="M 4 14 L 16 14 M 4 26 L 16 26 M 32 20 L 36 20 M 12 8 Q 24 9 32 20 Q 24 31 12 32 Q 18 20 12 8 Z" fill="currentColor" fill-opacity="0.1" />`,
    svgIconIec: `<rect x="10" y="8" width="20" height="24" rx="2" fill="currentColor" fill-opacity="0.1" /><text x="20" y="24" text-anchor="middle" font-size="11" font-weight="bold" fill="currentColor">≥1</text><path d="M 4 14 L 10 14 M 4 26 L 10 26 M 30 20 L 36 20" />`,
  },
  {
    id: "not_gate",
    type: "not_gate",
    name: "Inversor NOT",
    shortName: "NOT",
    category: "logica-digital",
    categoryLabel: "Lógica Digital",
    description: "Negación lógica booleana (Y = ¬A).",
    defaultVal: "1",
    unit: "TTL",
    physicsEquation: "Y = ¬A",
    academicSummary: "Invierte el nivel lógico de entrada con transición analógica suave.",
    spiceModelLevel: "Inversor analógico con retardo t_pd",
    commercialSeries: ["74HC04", "74LS04"],
    packageFootprint: "DIP-14",
    tags: ["inversor", "compuerta not", "7404", "digital", "not", "negador"],
    svgIconIeee: `<path d="M 4 20 L 14 20 M 30 20 L 36 20 M 14 10 L 26 20 L 14 30 Z" fill="currentColor" fill-opacity="0.1" /><circle cx="28" cy="20" r="2" />`,
    svgIconIec: `<rect x="10" y="8" width="18" height="24" rx="2" fill="currentColor" fill-opacity="0.1" /><text x="19" y="24" text-anchor="middle" font-size="12" font-weight="bold" fill="currentColor">1</text><circle cx="30" cy="20" r="2" /><path d="M 4 20 L 10 20 M 32 20 L 36 20" />`,
  },
  {
    id: "nand_gate",
    type: "nand_gate",
    name: "Compuerta NAND",
    shortName: "NAND",
    category: "logica-digital",
    categoryLabel: "Lógica Digital",
    description: "Compuerta universal NOT-AND (Y = ¬(A · B)).",
    defaultVal: "1",
    unit: "TTL",
    physicsEquation: "Y = ¬(A ∧ B)",
    academicSummary: "Compuerta lógica completa: permite construir cualquier circuito combinatorio o secuencial.",
    spiceModelLevel: "Subcircuito NAND",
    commercialSeries: ["74HC00", "74LS00"],
    packageFootprint: "DIP-14",
    tags: ["compuerta nand", "no y", "7400", "digital", "nand", "universal"],
    svgIconIeee: `<path d="M 4 14 L 14 14 M 4 26 L 14 26 M 32 20 L 36 20 M 14 8 L 22 8 C 27 8, 28 14, 28 20 C 28 26, 27 32, 22 32 L 14 32 Z" fill="currentColor" fill-opacity="0.1" /><circle cx="30" cy="20" r="2" />`,
    svgIconIec: `<rect x="10" y="8" width="20" height="24" rx="2" fill="currentColor" fill-opacity="0.1" /><text x="20" y="24" text-anchor="middle" font-size="12" font-weight="bold" fill="currentColor">&amp;</text><circle cx="32" cy="20" r="2" /><path d="M 4 14 L 10 14 M 4 26 L 10 26 M 34 20 L 36 20" />`,
  },
  {
    id: "nor_gate",
    type: "nor_gate",
    name: "Compuerta NOR",
    shortName: "NOR",
    category: "logica-digital",
    categoryLabel: "Lógica Digital",
    description: "Compuerta universal NOT-OR (Y = ¬(A + B)).",
    defaultVal: "1",
    unit: "TTL",
    physicsEquation: "Y = ¬(A ∨ B)",
    academicSummary: "Compuerta universal alternativa para síntesis digital directa.",
    spiceModelLevel: "Subcircuito NOR",
    commercialSeries: ["74HC02", "74LS02"],
    packageFootprint: "DIP-14",
    tags: ["compuerta nor", "no o", "7402", "digital", "nor", "universal"],
    svgIconIeee: `<path d="M 4 14 L 16 14 M 4 26 L 16 26 M 34 20 L 36 20 M 12 8 Q 23 9 30 20 Q 23 31 12 32 Q 18 20 12 8 Z" fill="currentColor" fill-opacity="0.1" /><circle cx="32" cy="20" r="2" />`,
    svgIconIec: `<rect x="10" y="8" width="20" height="24" rx="2" fill="currentColor" fill-opacity="0.1" /><text x="20" y="24" text-anchor="middle" font-size="11" font-weight="bold" fill="currentColor">≥1</text><circle cx="32" cy="20" r="2" /><path d="M 4 14 L 10 14 M 4 26 L 10 26 M 34 20 L 36 20" />`,
  },
  {
    id: "xor_gate",
    type: "xor_gate",
    name: "Compuerta XOR",
    shortName: "XOR",
    category: "logica-digital",
    categoryLabel: "Lógica Digital",
    description: "OR exclusiva y generador de paridad (Y = A ⊕ B).",
    defaultVal: "1",
    unit: "TTL",
    physicsEquation: "Y = A ⊕ B = A¬B + ¬AB",
    academicSummary: "Imprescindible para sumadores aritméticos (Half/Full Adder) y comparadores.",
    spiceModelLevel: "Subcircuito XOR",
    commercialSeries: ["74HC86", "74LS86"],
    packageFootprint: "DIP-14",
    tags: ["compuerta xor", "or exclusiva", "7486", "digital", "xor", "paridad"],
    svgIconIeee: `<path d="M 4 14 L 16 14 M 4 26 L 16 26 M 32 20 L 36 20 M 9 8 Q 15 20 9 32 M 13 8 Q 24 9 32 20 Q 24 31 13 32 Q 19 20 13 8 Z" fill="currentColor" fill-opacity="0.1" />`,
    svgIconIec: `<rect x="10" y="8" width="20" height="24" rx="2" fill="currentColor" fill-opacity="0.1" /><text x="20" y="24" text-anchor="middle" font-size="12" font-weight="bold" fill="currentColor">=1</text><path d="M 4 14 L 10 14 M 4 26 L 10 26 M 30 20 L 36 20" />`,
  },
  {
    id: "flipflop_d",
    type: "flipflop_d",
    name: "Flip-Flop Tipo D (74HC74)",
    shortName: "FF-D",
    category: "logica-digital",
    categoryLabel: "Lógica Digital",
    description: "Biestable disparado por flanco de subida con entradas asíncronas Preset y Clear.",
    defaultVal: "5",
    unit: "V",
    physicsEquation: "Q_{n+1} = D \\quad (\\text{al flanco } 0 \\rightarrow 1 \\text{ de CLK})",
    academicSummary: "Elemento básico de memoria sincrónica para registros de almacenamiento y divisores de frecuencia.",
    spiceModelLevel: "CI Lógico Secuencial TTL/CMOS",
    hasActiveBehavior: true,
    commercialSeries: ["74HC74", "74LS74", "CD4013"],
    packageFootprint: "DIP-14 / SOIC-14",
    tags: ["flip flop d", "7474", "74hc74", "d-ff", "biestable", "memoria", "registro", "reloj", "secuencial"],
    svgIconIeee: `<rect x="10" y="6" width="20" height="28" rx="2" fill="currentColor" fill-opacity="0.1" stroke="currentColor" /><path d="M 10 18 L 16 20 L 10 22 M 4 12 L 10 12 M 4 20 L 10 20 M 30 12 L 36 12 M 30 28 L 36 28" />`,
    svgIconIec: `<rect x="10" y="6" width="20" height="28" rx="2" fill="currentColor" fill-opacity="0.1" stroke="currentColor" /><path d="M 10 18 L 16 20 L 10 22 M 4 12 L 10 12 M 4 20 L 10 20 M 30 12 L 36 12 M 30 28 L 36 28" />`,
  },
  {
    id: "flipflop_jk",
    type: "flipflop_jk",
    name: "Flip-Flop JK (74HC73)",
    shortName: "FF-JK",
    category: "logica-digital",
    categoryLabel: "Lógica Digital",
    description: "Biestable universal con modo basculación (Toggle) cuando J=1 y K=1.",
    defaultVal: "5",
    unit: "V",
    physicsEquation: "Q_{n+1} = J \\bar{Q}_n + \\bar{K} Q_n",
    academicSummary: "Flip-flop universal para diseño de contadores asíncronos y síncronos binarios/décadas.",
    spiceModelLevel: "CI Lógico Secuencial TTL/CMOS",
    hasActiveBehavior: true,
    commercialSeries: ["74HC73", "74LS73", "74HC76", "CD4027"],
    packageFootprint: "DIP-14 / DIP-16",
    tags: ["flip flop jk", "7473", "74hc73", "jk-ff", "toggle", "contador", "secuencial", "biestable"],
    svgIconIeee: `<rect x="10" y="6" width="20" height="28" rx="2" fill="currentColor" fill-opacity="0.1" stroke="currentColor" /><path d="M 10 18 L 16 20 L 10 22 M 4 10 L 10 10 M 4 20 L 10 20 M 4 30 L 10 30 M 30 10 L 36 10 M 30 30 L 36 30" />`,
    svgIconIec: `<rect x="10" y="6" width="20" height="28" rx="2" fill="currentColor" fill-opacity="0.1" stroke="currentColor" /><path d="M 10 18 L 16 20 L 10 22 M 4 10 L 10 10 M 4 20 L 10 20 M 4 30 L 10 30 M 30 10 L 36 10 M 30 30 L 36 30" />`,
  },
  {
    id: "bcd_to_7seg",
    type: "bcd_to_7seg",
    name: "Decodificador BCD a 7 Segmentos (74HC47)",
    shortName: "BCD-7SEG",
    category: "logica-digital",
    categoryLabel: "Lógica Digital",
    description: "Decodificador combinacional de código binario 0–9 a segmentos a..g para display numérico.",
    defaultVal: "5",
    unit: "V",
    physicsEquation: "\\text{BCD}(A,B,C,D) \\rightarrow (a,b,c,d,e,f,g)",
    academicSummary: "Convierte nibbles BCD directamente en patrones de encendido de dígitos de 7 segmentos.",
    spiceModelLevel: "CI Decodificador BCD",
    hasActiveBehavior: true,
    commercialSeries: ["74HC47", "74LS47", "74HC48", "CD4511"],
    packageFootprint: "DIP-16",
    tags: ["bcd a 7 segmentos", "7447", "74hc47", "decodificador", "display", "driver", "segmentos"],
    svgIconIeee: `<rect x="10" y="4" width="20" height="32" rx="2" fill="currentColor" fill-opacity="0.1" stroke="currentColor" /><text x="20" y="22" text-anchor="middle" font-size="8" font-weight="bold" fill="currentColor">BCD</text>`,
    svgIconIec: `<rect x="10" y="4" width="20" height="32" rx="2" fill="currentColor" fill-opacity="0.1" stroke="currentColor" /><text x="20" y="22" text-anchor="middle" font-size="8" font-weight="bold" fill="currentColor">BCD</text>`,
  },
  {
    id: "shift_register_595",
    type: "shift_register_595",
    name: "Registro de Desplazamiento 8-Bit SIPO (74HC595)",
    shortName: "74HC595",
    category: "logica-digital",
    categoryLabel: "Lógica Digital",
    description: "Registro serie a paralelo de 8 bits con cerrojo de almacenamiento (Latch) y salida tri-state.",
    defaultVal: "5",
    unit: "V",
    physicsEquation: "\\text{SER} \\xrightarrow{\\text{SRCLK}} Q_{0..7} \\xrightarrow{\\text{RCLK}} \\text{Latch Outputs}",
    academicSummary: "Expansor de pines GPIO mediante protocolo serie síncrono para matrices de LEDs y relés.",
    spiceModelLevel: "CI Lógico MSI Registros",
    hasActiveBehavior: true,
    commercialSeries: ["74HC595", "74LS595", "TPIC6B595"],
    packageFootprint: "DIP-16 / SOIC-16",
    tags: ["74hc595", "registro desplazamiento", "shift register", "sipo", "expansor gpio", "serie paralelo"],
    svgIconIeee: `<rect x="10" y="4" width="20" height="32" rx="2" fill="currentColor" fill-opacity="0.1" stroke="currentColor" /><text x="20" y="22" text-anchor="middle" font-size="8" font-weight="bold" fill="currentColor">595</text>`,
    svgIconIec: `<rect x="10" y="4" width="20" height="32" rx="2" fill="currentColor" fill-opacity="0.1" stroke="currentColor" /><text x="20" y="22" text-anchor="middle" font-size="8" font-weight="bold" fill="currentColor">595</text>`,
  },

  // ─── MCUS Y SOcs ──────────────────────────────────────────────────────
  {
    id: "arduino_uno",
    type: "arduino_uno",
    name: "Arduino Uno (ATmega328P)",
    shortName: "ARDUINO",
    category: "digitales-mcus",
    categoryLabel: "MCUs",
    description: "Placa de microcontrolador AVR con puertos digitales y analógicos.",
    defaultVal: "1",
    unit: "MCU",
    academicSummary: "Co-simulación digital-analógica sincronizada paso a paso por ciclo con el solver MNA.",
    spiceModelLevel: "Co-simulación runtime AVR/TypeScript",
    hasActiveBehavior: true,
    tags: ["arduino", "mcu", "atmega328p", "microcontrolador", "uno", "avr", "embedded"],
    svgIconIeee: `<rect x="6" y="8" width="28" height="24" rx="2" fill="currentColor" fill-opacity="0.1" /><circle cx="12" cy="14" r="2" /><path d="M 12 24 H 28" />`,
    svgIconIec: `<rect x="6" y="8" width="28" height="24" rx="2" /><text x="20" y="23" text-anchor="middle" font-size="7" font-weight="bold" fill="currentColor">MCU</text>`,
  },
  {
    id: "esp32",
    type: "esp32",
    name: "ESP32 SoC (Dual-Core)",
    shortName: "ESP32",
    category: "digitales-mcus",
    categoryLabel: "MCUs",
    description: "Microcontrolador IoT de alto rendimiento de 32 bits.",
    defaultVal: "1",
    unit: "SoC",
    academicSummary: "Mapeo de pines GPIO, DAC, ADC y comunicaciones serie con lógica de 3.3V.",
    spiceModelLevel: "Co-simulación digital de pines",
    hasActiveBehavior: true,
    tags: ["esp32", "wifi", "bluetooth", "mcu", "espressif", "iot", "dual core"],
    svgIconIeee: `<rect x="8" y="8" width="24" height="24" rx="2" fill="currentColor" fill-opacity="0.1" /><path d="M 14 14 H 26 V 26 H 14 Z" />`,
    svgIconIec: `<rect x="8" y="8" width="24" height="24" rx="2" /><text x="20" y="23" text-anchor="middle" font-size="6.5" font-weight="bold" fill="currentColor">ESP32</text>`,
  },
  {
    id: "raspberry_pi_pico",
    type: "raspberry_pi_pico",
    name: "Raspberry Pi Pico (RP2040)",
    shortName: "PICO",
    category: "digitales-mcus",
    categoryLabel: "MCUs",
    description: "Microcontrolador ARM Cortex-M0+ con puertos I/O configurables.",
    defaultVal: "1",
    unit: "RP2040",
    academicSummary: "Entorno para emulación embebida y control de periféricos digitales.",
    spiceModelLevel: "Co-simulación digital de pines",
    hasActiveBehavior: true,
    tags: ["raspberry", "pico", "rp2040", "mcu", "arm", "cortex"],
    svgIconIeee: `<rect x="12" y="6" width="16" height="28" rx="2" fill="currentColor" fill-opacity="0.1" /><circle cx="20" cy="14" r="2" />`,
    svgIconIec: `<rect x="12" y="6" width="16" height="28" rx="2" /><text x="20" y="23" text-anchor="middle" font-size="6" font-weight="bold" fill="currentColor">PICO</text>`,
  },

  // ─── ANOTACIONES Y PUERTOS EDA ─────────────────────────────────────────
  {
    id: "net_label",
    type: "net_label",
    name: "Puerto de Señal (Net Label)",
    shortName: "NET",
    category: "anotaciones",
    categoryLabel: "Puertos EDA",
    description: "Interconexión virtual nombrada sin cables físicos cruzados.",
    defaultVal: "NET_A",
    unit: "EDA",
    hotkey: "N",
    academicSummary: "Unifica nodos eléctricos bajo un mismo identificador semántico en el grafo DSU.",
    spiceModelLevel: "Directiva de nodo con nombre",
    extraProps: { terminalType: "signal" },
    tags: ["puerto de red", "net label", "puerto", "terminal", "etiqueta", "bus", "signal"],
    svgIconIeee: `<polygon points="6,20 14,10 34,10 34,30 14,30" fill="#38BDF8" fill-opacity="0.2" /><circle cx="6" cy="20" r="2.5" fill="#38BDF8" /><text x="22" y="23" text-anchor="middle" font-size="8" font-family="monospace" font-weight="bold" fill="#38BDF8">NET</text>`,
    svgIconIec: `<polygon points="6,20 14,10 34,10 34,30 14,30" fill="#38BDF8" fill-opacity="0.2" /><circle cx="6" cy="20" r="2.5" fill="#38BDF8" />`,
  },
  {
    id: "port_vcc",
    type: "net_label",
    name: "Riel de Alimentación (+5V)",
    shortName: "+5V",
    category: "anotaciones",
    categoryLabel: "Puertos EDA",
    description: "Riel de alimentación virtual VCC (+5V referenciado a GND).",
    defaultVal: "+5V",
    unit: "+5V",
    academicSummary: "Inyecta potencial fijo de +5V al nodo conectado según estándar TTL.",
    spiceModelLevel: "Fuente virtual fija de 5V",
    extraProps: { terminalType: "power" },
    tags: ["vcc", "+5v", "alimentacion", "power port", "riel"],
    svgIconIeee: `<line x1="20" y1="32" x2="20" y2="18" stroke="#F59E0B" stroke-width="2" /><polygon points="14,18 20,8 26,18" fill="#F59E0B" fill-opacity="0.3" stroke="#F59E0B" /><circle cx="20" cy="32" r="2.5" fill="#F59E0B" /><text x="20" y="6" text-anchor="middle" font-size="7" font-family="monospace" font-weight="bold" fill="#F59E0B">+5V</text>`,
    svgIconIec: `<line x1="20" y1="32" x2="20" y2="18" stroke="#F59E0B" stroke-width="2" /><circle cx="20" cy="14" r="4" fill="#F59E0B" fill-opacity="0.3" stroke="#F59E0B" />`,
  },
  {
    id: "port_vdd",
    type: "net_label",
    name: "Riel de Alimentación (+3.3V)",
    shortName: "+3.3V",
    category: "anotaciones",
    categoryLabel: "Puertos EDA",
    description: "Riel de alimentación lógica de baja tensión para MCUs.",
    defaultVal: "+3.3V",
    unit: "+3.3V",
    academicSummary: "Riel de alimentación de 3.3V estándar para ESP32, ARM y CMOS moderno.",
    spiceModelLevel: "Fuente virtual fija de 3.3V",
    extraProps: { terminalType: "power" },
    tags: ["vdd", "+3.3v", "alimentacion", "power", "3.3v", "mcu"],
    svgIconIeee: `<line x1="20" y1="32" x2="20" y2="18" stroke="#F59E0B" stroke-width="2" /><polygon points="14,18 20,8 26,18" fill="#F59E0B" fill-opacity="0.3" stroke="#F59E0B" /><circle cx="20" cy="32" r="2.5" fill="#F59E0B" /><text x="20" y="6" text-anchor="middle" font-size="6.5" font-family="monospace" font-weight="bold" fill="#F59E0B">+3.3V</text>`,
    svgIconIec: `<line x1="20" y1="32" x2="20" y2="18" stroke="#F59E0B" stroke-width="2" /><circle cx="20" cy="14" r="4" fill="#F59E0B" fill-opacity="0.3" stroke="#F59E0B" />`,
  },
  {
    id: "text_note",
    type: "text_note",
    name: "Nota de Ingeniería",
    shortName: "NOTE",
    category: "anotaciones",
    categoryLabel: "Anotaciones",
    description: "Bloque de texto, fórmulas y documentación técnica en el esquemático.",
    defaultVal: "Nota de Ingeniería",
    unit: "DOC",
    academicSummary: "Anotaciones de diseño, títulos de láminas y especificaciones de laboratorio.",
    spiceModelLevel: "Comentario (* en netlist)",
    tags: ["nota", "texto", "anotacion", "comentario", "descripcion", "esquema", "documentacion", "markdown", "titulo", "aviso"],
    svgIconIeee: `<rect x="6" y="8" width="28" height="24" rx="3" fill="currentColor" fill-opacity="0.12" /><line x1="10" y1="14" x2="30" y2="14" stroke-width="2.5" /><line x1="10" y1="20" x2="26" y2="20" /><line x1="10" y1="25" x2="20" y2="25" />`,
    svgIconIec: `<rect x="6" y="8" width="28" height="24" rx="3" fill="currentColor" fill-opacity="0.12" /><line x1="10" y1="14" x2="30" y2="14" stroke-width="2.5" /><line x1="10" y1="20" x2="26" y2="20" />`,
  },

  // ─── MACROMODELOS ─────────────────────────────────────────────────────
  {
    id: "subcircuit",
    type: "x",
    name: "Subcircuito SPICE (.SUBCKT)",
    shortName: "SPICE-X",
    category: "macromodelos",
    categoryLabel: "Macromodelos",
    description: "Macromodelo jerárquico importado con mapeo dinámico de pines.",
    defaultVal: "1",
    unit: "X",
    academicSummary: "Permite importar modelos comerciales completos de fabricantes (Texas Instruments, ADI, etc.).",
    spiceModelLevel: "X (Subcircuito jerárquico SPICE)",
    tags: ["subcircuito", "macromodelo", "spice", "subckt", "chip", "dip", "ic", "modulo", "ne555", "timer", "555"],
    svgIconIeee: `<rect x="6" y="6" width="28" height="28" rx="3" stroke-dasharray="3 2" /><text x="20" y="24" text-anchor="middle" font-size="10" fill="currentColor">X</text>`,
    svgIconIec: `<rect x="6" y="6" width="28" height="28" rx="3" stroke-dasharray="3 2" /><text x="20" y="24" text-anchor="middle" font-size="10" fill="currentColor">X</text>`,
  },
];
