import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const rootDir = resolve(scriptDir, "..");
const catalogPath = resolve(rootDir, "feedback/contracts/catalog.v1.json");
const outputs = {
  schema: resolve(rootDir, "feedback/contracts/feedback-event.v1.schema.json"),
  typescript: resolve(rootDir, "src/feedback/contracts.generated.ts"),
  rust: resolve(rootDir, "src-tauri/src/feedback/schema.generated.rs"),
};
const checkOnly = process.argv.includes("--check");

const catalog = JSON.parse(await readFile(catalogPath, "utf8"));

function pascalCase(value) {
  return value
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map(part => part.charAt(0).toUpperCase() + part.slice(1).toLowerCase())
    .join("");
}

function camelToSnake(value) {
  return value
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .replace(/[^A-Za-z0-9]+/g, "_")
    .toLowerCase();
}

function rustVariant(value) {
  const candidate = pascalCase(value);
  return /^[0-9]/.test(candidate) ? `Value${candidate}` : candidate;
}

function jsonSchemaForField(field) {
  let schema;
  switch (field.type) {
    case "string":
      schema = { type: "string" };
      break;
    case "number":
      schema = { type: "number" };
      break;
    case "integer":
      schema = { type: "integer" };
      break;
    case "boolean":
      schema = { type: "boolean" };
      break;
    case "enum":
      schema = { type: "string", enum: field.values };
      break;
    case "integerMap":
      schema = {
        type: "object",
        additionalProperties: { type: "integer", minimum: 0 },
      };
      break;
    default:
      throw new Error(`Tipo de campo no soportado: ${field.type}`);
  }
  if (field.min !== undefined) schema.minimum = field.min;
  if (field.max !== undefined) schema.maximum = field.max;
  if (field.maxLength !== undefined) schema.maxLength = field.maxLength;
  if (field.maxProperties !== undefined) schema.maxProperties = field.maxProperties;
  return schema;
}

function generateJsonSchema() {
  const commonProperties = {
    schemaVersion: { const: catalog.schemaVersion },
    eventId: { type: "string", minLength: 1, maxLength: 128 },
    occurredAtUnixMs: { type: "integer", minimum: 0 },
    sessionId: { type: "string", minLength: 1, maxLength: 128 },
    runId: { type: "string", minLength: 1, maxLength: 128 },
    workspaceId: { type: "string", minLength: 1, maxLength: 128 },
    appVersion: { type: "string", minLength: 1, maxLength: 64 },
    gitRevision: { type: "string", minLength: 1, maxLength: 64 },
  };
  const commonRequired = [
    "schemaVersion",
    "eventId",
    "occurredAtUnixMs",
    "sessionId",
    "appVersion",
    "privacyClass",
    "kind",
    "payload",
  ];

  return `${JSON.stringify({
    $schema: "https://json-schema.org/draft/2020-12/schema",
    $id: catalog.schemaId,
    title: "Astryd Sophia Feedback Event V1",
    description: "Contrato local-first para eventos de retroalimentacion.",
    oneOf: catalog.events.map(event => {
      const payloadProperties = Object.fromEntries(
        event.fields.map(field => [field.name, jsonSchemaForField(field)]),
      );
      return {
        type: "object",
        additionalProperties: false,
        required: commonRequired,
        properties: {
          ...commonProperties,
          privacyClass: { const: event.privacyClass },
          kind: { const: event.kind },
          payload: {
            type: "object",
            additionalProperties: false,
            required: event.fields.filter(field => !field.optional).map(field => field.name),
            properties: payloadProperties,
          },
        },
      };
    }),
  }, null, 2)}\n`;
}

function tsType(field) {
  switch (field.type) {
    case "string":
      return "string";
    case "number":
    case "integer":
      return "number";
    case "boolean":
      return "boolean";
    case "enum":
      return field.values.map(value => JSON.stringify(value)).join(" | ");
    case "integerMap":
      return "Readonly<Record<string, number>>";
    default:
      throw new Error(`Tipo TS no soportado: ${field.type}`);
  }
}

function payloadName(event) {
  return `${pascalCase(event.kind)}PayloadV1`;
}

function generateTypeScript() {
  const lines = [
    "// @generated by scripts/generate_feedback_contracts.mjs; do not edit.",
    "",
    `export const FEEDBACK_SCHEMA_VERSION = ${catalog.schemaVersion} as const;`,
    "",
    "export const FEEDBACK_PRIVACY_CLASSES = [",
    ...catalog.privacyClasses.map(value => `  ${JSON.stringify(value)},`),
    "] as const;",
    "export type FeedbackPrivacyClass = (typeof FEEDBACK_PRIVACY_CLASSES)[number];",
    "",
    "export const FEEDBACK_EVENT_KINDS = [",
    ...catalog.events.map(event => `  ${JSON.stringify(event.kind)},`),
    "] as const;",
    "export type FeedbackEventKind = (typeof FEEDBACK_EVENT_KINDS)[number];",
    "",
    "export const FEEDBACK_EVENT_PRIVACY = {",
    ...catalog.events.map(event => `  ${JSON.stringify(event.kind)}: ${JSON.stringify(event.privacyClass)},`),
    "} as const satisfies Readonly<Record<FeedbackEventKind, FeedbackPrivacyClass>>;",
    "",
    "export interface FeedbackEventEnvelopeV1 {",
    "  readonly schemaVersion: typeof FEEDBACK_SCHEMA_VERSION;",
    "  readonly eventId: string;",
    "  readonly occurredAtUnixMs: number;",
    "  readonly sessionId: string;",
    "  readonly runId?: string;",
    "  readonly workspaceId?: string;",
    "  readonly appVersion: string;",
    "  readonly gitRevision?: string;",
    "}",
    "",
  ];

  for (const event of catalog.events) {
    lines.push(`export interface ${payloadName(event)} {`);
    for (const field of event.fields) {
      lines.push(`  readonly ${field.name}${field.optional ? "?" : ""}: ${tsType(field)};`);
    }
    lines.push("}", "");
  }

  lines.push(
    "export type FeedbackEventV1 =",
    ...catalog.events.map((event, index) => {
      const prefix = index === 0 ? "  " : "  | ";
      return `${prefix}(FeedbackEventEnvelopeV1 & { readonly privacyClass: ${JSON.stringify(event.privacyClass)}; readonly kind: ${JSON.stringify(event.kind)}; readonly payload: ${payloadName(event)} })`;
    }),
    ";",
    "",
    "export function expectedPrivacyClass(kind: FeedbackEventKind): FeedbackPrivacyClass {",
    "  return FEEDBACK_EVENT_PRIVACY[kind];",
    "}",
  );

  return `${lines.join("\n")}\n`;
}

function rustType(field, event) {
  if (field.type === "enum") {
    return `${pascalCase(event.kind)}${pascalCase(field.name)}Value`;
  }
  switch (field.type) {
    case "string":
      return "String";
    case "number":
      return "f64";
    case "integer":
      return "u64";
    case "boolean":
      return "bool";
    case "integerMap":
      return "BTreeMap<String, u64>";
    default:
      throw new Error(`Tipo Rust no soportado: ${field.type}`);
  }
}

function rustPrivacyVariant(value) {
  return rustVariant(value);
}

function generateRust() {
  const lines = [
    "// @generated by scripts/generate_feedback_contracts.mjs; do not edit.",
    "use serde::{Deserialize, Serialize};",
    "use std::collections::BTreeMap;",
    "",
    `pub const FEEDBACK_SCHEMA_VERSION: u16 = ${catalog.schemaVersion};`,
    "",
    "#[derive(Serialize, Deserialize, Clone, Copy, Debug, PartialEq, Eq)]",
    "pub enum FeedbackPrivacyClass {",
    ...catalog.privacyClasses.flatMap(value => [
      `    #[serde(rename = ${JSON.stringify(value)})]`,
      `    ${rustPrivacyVariant(value)},`,
    ]),
    "}",
    "",
  ];

  for (const event of catalog.events) {
    for (const field of event.fields.filter(field => field.type === "enum")) {
      const enumName = rustType(field, event);
      lines.push(
        "#[derive(Serialize, Deserialize, Clone, Copy, Debug, PartialEq, Eq)]",
        `pub enum ${enumName} {`,
      );
      for (const value of field.values) {
        lines.push(
          `    #[serde(rename = ${JSON.stringify(value)})]`,
          `    ${rustVariant(value)},`,
        );
      }
      lines.push("}", "");
    }

    lines.push(
      "#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]",
      "#[serde(rename_all = \"camelCase\")]",
      `pub struct ${payloadName(event)} {`,
    );
    for (const field of event.fields) {
      if (field.optional) {
        lines.push("    #[serde(default, skip_serializing_if = \"Option::is_none\")]");
      }
      const baseType = rustType(field, event);
      lines.push(`    pub ${camelToSnake(field.name)}: ${field.optional ? `Option<${baseType}>` : baseType},`);
    }
    lines.push("}", "");
  }

  lines.push(
    "#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]",
    "#[serde(tag = \"kind\", content = \"payload\")]",
    "pub enum FeedbackEventDataV1 {",
  );
  for (const event of catalog.events) {
    lines.push(
      `    #[serde(rename = ${JSON.stringify(event.kind)})]`,
      `    ${rustVariant(event.kind)}(${payloadName(event)}),`,
    );
  }
  lines.push(
    "}",
    "",
    "impl FeedbackEventDataV1 {",
    "    pub fn kind(&self) -> &'static str {",
    "        match self {",
    ...catalog.events.map(event => `            Self::${rustVariant(event.kind)}(_) => ${JSON.stringify(event.kind)},`),
    "        }",
    "    }",
    "",
    "    pub fn expected_privacy_class(&self) -> FeedbackPrivacyClass {",
    "        match self {",
    ...catalog.events.map(event => `            Self::${rustVariant(event.kind)}(_) => FeedbackPrivacyClass::${rustPrivacyVariant(event.privacyClass)},`),
    "        }",
    "    }",
    "}",
    "",
    "#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]",
    "#[serde(rename_all = \"camelCase\")]",
    "pub struct FeedbackEventV1 {",
    "    pub schema_version: u16,",
    "    pub event_id: String,",
    "    pub occurred_at_unix_ms: u64,",
    "    pub session_id: String,",
    "    #[serde(default, skip_serializing_if = \"Option::is_none\")]",
    "    pub run_id: Option<String>,",
    "    #[serde(default, skip_serializing_if = \"Option::is_none\")]",
    "    pub workspace_id: Option<String>,",
    "    pub app_version: String,",
    "    #[serde(default, skip_serializing_if = \"Option::is_none\")]",
    "    pub git_revision: Option<String>,",
    "    pub privacy_class: FeedbackPrivacyClass,",
    "    #[serde(flatten)]",
    "    pub event: FeedbackEventDataV1,",
    "}",
    "",
    "impl FeedbackEventV1 {",
    "    pub fn validate_envelope(&self) -> Result<(), &'static str> {",
    "        if self.schema_version != FEEDBACK_SCHEMA_VERSION {",
    "            return Err(\"unsupported schemaVersion\");",
    "        }",
    "        if self.event_id.is_empty() || self.event_id.len() > 128 {",
    "            return Err(\"invalid eventId\");",
    "        }",
    "        if self.session_id.is_empty() || self.session_id.len() > 128 {",
    "            return Err(\"invalid sessionId\");",
    "        }",
    "        if self",
    "            .workspace_id",
    "            .as_ref()",
    "            .is_some_and(|value| value.is_empty() || value.len() > 128)",
    "        {",
    "            return Err(\"invalid workspaceId\");",
    "        }",
    "        if self.app_version.is_empty() || self.app_version.len() > 64 {",
    "            return Err(\"invalid appVersion\");",
    "        }",
    "        if self.privacy_class != self.event.expected_privacy_class() {",
    "            return Err(\"privacyClass does not match event kind\");",
    "        }",
    "        Ok(())",
    "    }",
    "}",
    "",
    "pub const FEEDBACK_EVENT_CATALOG: &[(&str, FeedbackPrivacyClass)] = &[",
    ...catalog.events.flatMap(event => {
      const tuple = `    (${JSON.stringify(event.kind)}, FeedbackPrivacyClass::${rustPrivacyVariant(event.privacyClass)}),`;
      // rustfmt expands tuples longer than its default single-line tuple heuristic.
      return tuple.length <= 68
        ? [tuple]
        : [
            "    (",
            `        ${JSON.stringify(event.kind)},`,
            `        FeedbackPrivacyClass::${rustPrivacyVariant(event.privacyClass)},`,
            "    ),",
          ];
    }),
    "];",
  );

  return `${lines.join("\n")}\n`;
}

async function updateOrCheck(path, content) {
  if (checkOnly) {
    let current;
    try {
      current = await readFile(path, "utf8");
    } catch {
      throw new Error(`Falta artefacto generado: ${path}`);
    }
    if (current !== content) {
      throw new Error(`Artefacto desactualizado: ${path}`);
    }
    return;
  }
  await writeFile(path, content, "utf8");
}

await updateOrCheck(outputs.schema, generateJsonSchema());
await updateOrCheck(outputs.typescript, generateTypeScript());
await updateOrCheck(outputs.rust, generateRust());

console.log(checkOnly
  ? "Contratos de feedback sincronizados."
  : "Contratos de feedback generados.");
