// ==========================================================================
// BIAANI INTERACTIVE FEATURE TOUR — CATÁLOGO DECLARATIVO DE PASOS
// ==========================================================================

import type { GuideStep, GuideTopic } from "./guide_types";

export const GUIDE_TOPICS: GuideTopic[] = [
  {
    id: "environment",
    title: "Anatomía y Entorno",
    icon: "🏛️",
    description: "Familiarización con la interfaz, gestión de proyectos y paneles principales.",
  },
  {
    id: "schematic",
    title: "Captura y Cableado",
    icon: "✏️",
    description: "Lienzo CAD, colocación de componentes, búsqueda rápida, rotación y cableado.",
  },
  {
    id: "simulation",
    title: "Simulación Física MNA",
    icon: "⚡",
    description: "Modos de análisis (Transitorio, DC, AC/Bode, Sensibilidad, PVT) y ejecución.",
  },
  {
    id: "instruments",
    title: "Laboratorio Virtual",
    icon: "🛠️",
    description: "Osciloscopio digital 4CH, Generador, Analizador Lógico, FFT y Optimizador.",
  },
  {
    id: "advanced",
    title: "Herramientas Avanzadas",
    icon: "🔬",
    description: "Inspector pedagógico de Matriz MNA (LaTeX), co-simulación MCU, reporte de errores y ajustes.",
  },
];

export const GUIDE_STEPS: GuideStep[] = [
  {
    id: "welcome",
    topicId: "environment",
    topicTitle: "Anatomía y Entorno",
    title: "Bienvenido a Biaani",
    description: "Biaani combina la precisión analítica de un solver en Rust mediante Análisis Nodal Modificado (MNA) con un lienzo CAD interactivo en Canvas 2D y diseño Glassmorphic.",
    targetSelector: "#logo-main-title",
    placement: "bottom",
    actionHint: "Navega con [◄] [►], Enter o selecciona un tema en la cabecera.",
  },
  {
    id: "project_management",
    topicId: "environment",
    topicTitle: "Anatomía y Entorno",
    title: "Gestión de Proyectos y Demos",
    description: "Crea esquemas en blanco, abre archivos de circuito (.biaani o .spice) o carga circuitos de ejemplo prediseñados (filtros, rectificadores, MCU, amplificadores).",
    targetSelector: "#app-header .header-project-group",
    placement: "bottom",
    shortcut: "Ctrl+N / Ctrl+O / Ctrl+S",
    actionButton: {
      label: "Cargar Filtro RC Demo",
      actionId: "load_demo_rc",
      icon: "📋",
    },
  },
  {
    id: "analysis_modes",
    topicId: "simulation",
    topicTitle: "Simulación Física MNA",
    title: "Modos de Análisis SPICE",
    description: "Selecciona entre Simulación Transitoria en tiempo real (TRAN), Punto de Operación (DC), Barrido en Frecuencia (AC/Bode), Sensibilidad, PSS, Polos/Ceros o análisis PVT.",
    targetSelector: "#analysis-mode-select",
    placement: "bottom",
    actionHint: "El modo Transitorio resuelve dinámicamente condensadores, bobinas y semiconductores.",
  },
  {
    id: "simulation_controls",
    topicId: "simulation",
    topicTitle: "Simulación Física MNA",
    title: "Control de Simulación en Vivo",
    description: "Inicia y detiene la resolución numérica de las leyes de Kirchhoff en tiempo real. Puedes pausar para inspeccionar estados estables o cambiar componentes al vuelo.",
    targetSelector: "#run-sim-btn",
    placement: "bottom",
    shortcut: "Espacio",
  },
  {
    id: "component_palette",
    topicId: "schematic",
    topicTitle: "Captura y Cableado",
    title: "Paleta de Componentes",
    description: "Biblioteca clasificada en Pasivos, Semiconductores, Fuentes, Circuitos Integrados (74xx), Potencia (IGBT/Triac/SCR), Actuadores y Microcontroladores.",
    targetSelector: "#sidebar-left",
    placement: "right",
    shortcut: "F9",
    requiresPanel: "left",
  },
  {
    id: "component_spotlight",
    topicId: "schematic",
    topicTitle: "Captura y Cableado",
    title: "Inserción Rápida con Spotlight (Ctrl+K)",
    description: "Busca e inserta cualquier componente al instante escribiendo su nombre o designador con coincidencia difusa inteligente (fuzzy search).",
    targetSelector: "#sidebar-left",
    placement: "right",
    shortcut: "Ctrl+K / /",
    actionButton: {
      label: "Abrir Spotlight Ahora",
      actionId: "open_spotlight",
      icon: "🔍",
    },
  },
  {
    id: "canvas_cad",
    topicId: "schematic",
    topicTitle: "Captura y Cableado",
    title: "Lienzo CAD y Rejilla de 20px",
    description: "El lienzo cuenta con ajuste magnético a rejilla (Snap a 20px), rotación con 'R', navegación fluida con pan (botón central) y zoom con la rueda.",
    targetSelector: "#circuit-canvas",
    placement: "center",
    actionHint: "R: Rotar · Supr: Eliminar · Rueda: Zoom · Botón central: Mover lienzo.",
  },
  {
    id: "wire_mode",
    topicId: "schematic",
    topicTitle: "Captura y Cableado",
    title: "Modo de Cableado Rápido",
    description: "Activa el trazado de cables para unir pines ortogonalmente. El motor detecta uniones eléctricas (nets) y verifica las reglas de circuito (ERC).",
    targetSelector: "#btn-wire-mode",
    placement: "right",
    shortcut: "W",
  },
  {
    id: "component_properties",
    topicId: "schematic",
    topicTitle: "Captura y Cableado",
    title: "Inspector de Propiedades y Valores Comerciales",
    description: "Edita parámetros físicos de cualquier componente seleccionado o ajústalos automáticamente al valor comercial estándar más cercano (series E12/E24/E96).",
    targetSelector: "#sidebar-right",
    placement: "left",
    shortcut: "F10",
    requiresPanel: "right",
  },
  {
    id: "instruments_dock",
    topicId: "instruments",
    topicTitle: "Laboratorio Virtual",
    title: "Centro de Instrumentación",
    description: "Accede al instrumental completo en el dock inferior (Osciloscopio, Generador de Señales, Analizador Lógico, FFT, Trazador de Curvas y Optimizador).",
    targetSelector: "#btn-dock-toggle-bottom",
    placement: "top",
    shortcut: "F8",
    requiresPanel: "dock",
  },
  {
    id: "oscilloscope",
    topicId: "instruments",
    topicTitle: "Laboratorio Virtual",
    title: "Osciloscopio Digital de 4 Canales",
    description: "Grafica voltajes en tiempo real con modos T-Y, X-Y (Lissajous) o canal matemático (MATH). Conecta sondas haciendo Shift+Clic en CH1–CH4 o arrastrando el canal al lienzo.",
    targetSelector: "#osc-header",
    placement: "top",
    actionHint: "Shift+Clic en CH1 o CH2 para colocar una sonda en cualquier nodo.",
    requiresPanel: "dock",
    requiresInstrumentTab: "oscilloscope",
    actionButton: {
      label: "Desplegar Osciloscopio",
      actionId: "open_oscilloscope",
      icon: "📈",
    },
  },
  {
    id: "digital_telemetry",
    topicId: "instruments",
    topicTitle: "Laboratorio Virtual",
    title: "Telemetría y Métricas en Tiempo Real",
    description: "Lectura instantánea de voltaje pico a pico (Vpp), valor eficaz (Vrms), frecuencia fundamental, ciclo de trabajo (Duty) y tiempos de conmutación.",
    targetSelector: "#osc-measurements-bar",
    placement: "top",
    requiresPanel: "dock",
    requiresInstrumentTab: "oscilloscope",
  },
  {
    id: "circuit_optimizer",
    topicId: "instruments",
    topicTitle: "Laboratorio Virtual",
    title: "Optimizador Paramétrico y Auto-Tuning",
    description: "Sintoniza automáticamente los valores de tu circuito (resistencias, condensadores, fuentes) para alcanzar metas de diseño específicas con algoritmos de optimización.",
    targetSelector: ".inst-tab[data-tab='optimizer'], #bottom-dock",
    placement: "top",
    requiresPanel: "dock",
    requiresInstrumentTab: "optimizer",
    actionButton: {
      label: "Ver Auto-Tuning",
      actionId: "open_optimizer",
      icon: "🎯",
    },
  },
  {
    id: "mna_inspector",
    topicId: "advanced",
    topicTitle: "Herramientas Avanzadas",
    title: "Inspector Pedagógico de Matriz MNA",
    description: "Visualiza la formulación matemática exacta del circuito: matrices de conductancia [G], matrices dinámicas [C] y vectores de excitación [B] renderizados en LaTeX con opción de copiado.",
    targetSelector: "#btn-mna-inspector",
    placement: "bottom",
    actionButton: {
      label: "Ver Matriz LaTeX Ahora",
      actionId: "open_mna_inspector",
      icon: "📐",
    },
  },
  {
    id: "mcu_cosimulation",
    topicId: "advanced",
    topicTitle: "Herramientas Avanzadas",
    title: "Co-simulación MCU (ESP32, AVR, 8051, PIC)",
    description: "Ejecuta microcontroladores interactuando con circuitos analógicos paso a paso. Incluye soporte para ESP32, Arduino (AVR), 8051 y PIC con editor y carga de firmware.",
    targetSelector: "#sidebar-left",
    placement: "right",
    requiresPanel: "left",
    actionHint: "Busca 'MCU' en la biblioteca de componentes o carga el demo 'Arduino + LED'.",
  },
  {
    id: "feedback_error_reporting",
    topicId: "advanced",
    topicTitle: "Herramientas Avanzadas",
    title: "Feedback, Diagnóstico y Comparativas",
    description: "Envía sugerencias, reporta discrepancias o compara resultados con otros simuladores (LTspice, Proteus) adjuntando capturas de referencia. Empaqueta el circuito, netlist SPICE y logs técnicos en 1 clic.",
    targetSelector: "#btn-feedback-trigger",
    placement: "bottom",
    shortcut: "F7 / Ctrl+Shift+B",
    actionButton: {
      label: "Abrir Ventana de Feedback",
      actionId: "open_feedback",
      icon: "💬",
    },
  },
  {
    id: "settings_precision",
    topicId: "advanced",
    topicTitle: "Herramientas Avanzadas",
    title: "Ajustes de Simulación y Precisión",
    description: "Configura el paso de tiempo transitorio (dt), tolerancias Newton-Raphson, estándar de simbología (IEEE americano vs IEC europeo) y preferencias del sistema.",
    targetSelector: "#settings-trigger-btn",
    placement: "bottom",
    actionButton: {
      label: "Abrir Ajustes",
      actionId: "open_settings",
      icon: "⚙️",
    },
  },
  {
    id: "guide_ready",
    topicId: "advanced",
    topicTitle: "Herramientas Avanzadas",
    title: "¡Todo Listo para Diseñar!",
    description: "Puedes volver a abrir este recorrido en cualquier momento presionando F1 o haciendo clic en el botón Guía de la cabecera.",
    targetSelector: "#logo-main-title",
    placement: "bottom",
    shortcut: "F1",
  },
];